import { products } from "./mockProducts";

export const CONTACT = {
  whatsapp: '8700758871',
  whatsappDisplay: '+91 8700758871',
  phone: '+91 8700758871',
  phoneRaw: 'tel:+918700758871',
  email: 'orders@dwarkaorthodontics.com',
  address: 'Dwarka, New Delhi - 110075',
  gst: '07ABCDE1234F1Z5',
};

export const announcements = [
  'Free shipping on all orders above ₹2,000 — Pan India delivery',
  'GST invoices on every order — clinic pricing available',
  'Same-day dispatch for orders placed before 2 PM (Mon–Sat)',
  'Bulk pricing for dental colleges & multi-chair clinics — WhatsApp for quotes',
];

export const brands = [
  { id: 1, name: '3M Unitek', slug: '3m-unitek', country: 'USA' },
  { id: 2, name: 'Ormco', slug: 'ormco', country: 'USA' },
  { id: 3, name: 'American Orthodontics', slug: 'american-orthodontics', country: 'USA' },
  { id: 4, name: 'Dentsply Sirona', slug: 'dentsply-sirona', country: 'USA' },
  { id: 5, name: 'GC Corporation', slug: 'gc-corporation', country: 'Japan' },
  { id: 6, name: 'Forestadent', slug: 'forestadent', country: 'Germany' },
  { id: 7, name: 'Dentaurum', slug: 'dentaurum', country: 'Germany' },
  { id: 8, name: 'DB Orthodontics', slug: 'db-orthodontics', country: 'UK' },
  { id: 9, name: 'Ortho Technology', slug: 'ortho-technology', country: 'USA' },
  { id: 10, name: 'Hu-Friedy', slug: 'hu-friedy', country: 'USA' },
];

export const categories = [
  {
    id: 1,
    name: 'Brackets',
    slug: 'brackets',
    description: 'Metal, ceramic, and self-ligating brackets of premium quality',
    productCount: 48,
    gradient: 'from-blue-50 to-blue-100',
    iconColor: 'text-blue-600',
    borderColor: 'border-blue-200',
    abbr: 'BR',
    image: "https://vossdental.com/wp-content/uploads/2021/01/rubber-bands-for-braces-scaled-1.jpg"
  },
  {
    id: 2,
    name: 'Wires & Springs',
    slug: 'wires-springs',
    description: 'NiTi, SS, and Beta-Ti wires in all dimensions',
    productCount: 62,
    gradient: 'from-slate-50 to-slate-100',
    iconColor: 'text-slate-600',
    borderColor: 'border-slate-200',
    abbr: 'WR',
    image: "https://r2dkmedia.dentalkart.com/media/catalog/product/1/2/123a10_3_1.jpg"
  },
  {
    id: 3,
    name: 'Bands & Tubes',
    slug: 'bands-tubes',
    description: 'Monoblock and convertible buccal tubes for all prescriptions',
    productCount: 34,
    gradient: 'from-indigo-50 to-indigo-100',
    iconColor: 'text-indigo-600',
    borderColor: 'border-indigo-200',
    abbr: 'BT',
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcQ85C9VMxLIn53b0oIcXQscuSKqXDEp23uWiw&s"
  },
  {
    id: 4,
    name: 'Elastics & Ligatures',
    slug: 'elastics',
    description: 'Power chains, elastic ligatures, and inter-arch elastics',
    productCount: 41,
    gradient: 'from-purple-50 to-purple-100',
    iconColor: 'text-purple-600',
    borderColor: 'border-purple-200',
    abbr: 'EL',
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcSA9W9TYdgBC0cDNYbHEtLJ88XPHDsP6keYFQ&s"
  },
    {
    id: 5,
    name: 'Pliers',
    slug: 'pliers',
    description: 'Weingart, bird-beak, ligature cutters, and specialty pliers',
    productCount: 55,
    gradient: 'from-zinc-50 to-zinc-100',
    iconColor: 'text-zinc-600',
    borderColor: 'border-zinc-200',
    abbr: 'PL',
    image: "https://image.made-in-china.com/202f0j00iSvVlAEJrZGf/Professional-Orthodontic-Pliers-for-Brace-Wire-Bending-Cutting-and-Adjusting-in-Dental-Clinic-Use.webp"
  },

  {
    id: 6,
    name: 'Adhesives & Bonding',
    slug: 'adhesives',
    description: 'Light-cure and self-cure bonding systems for reliable bond strength',
    productCount: 22,
    gradient: 'from-amber-50 to-amber-100',
    iconColor: 'text-amber-600',
    borderColor: 'border-amber-200',
    abbr: 'AD',
    image: "https://azdentall.com/cdn/shop/files/a2_60ea63ce-d147-475c-a5f4-c61d1fb6a815.jpg?v=1711106743&width=1200"
  },

  // {
  //   id: 7,
  //   name: 'Instruments',
  //   slug: 'instruments',
  //   description: 'Orthodontic scalers, explorers, and chair-side instruments',
  //   productCount: 38,
  //   gradient: 'from-teal-50 to-teal-100',
  //   iconColor: 'text-teal-600',
  //   borderColor: 'border-teal-200',
  //   abbr: 'IN',
  // },
  // {
  //   id: 7,
  //   name: 'Aligner Accessories',
  //   slug: 'aligner-accessories',
  //   description: 'Chewies, IPR strips, aligner removal tools, and more',
  //   productCount: 19,
  //   gradient: 'from-sky-50 to-sky-100',
  //   iconColor: 'text-sky-600',
  //   borderColor: 'border-sky-200',
  //   abbr: 'AL',
  // },
  // {
  //   id: 9,
  //   name: 'Retainers',
  //   slug: 'retainers',
  //   description: 'Hawley, Essix, and fixed retainer systems',
  //   productCount: 14,
  //   gradient: 'from-green-50 to-green-100',
  //   iconColor: 'text-green-600',
  //   borderColor: 'border-green-200',
  //   abbr: 'RT',
  // },
  {
    id: 7,
    name: 'Miscellaneous',
    slug: 'miscellaneous',
    description: 'Separators, molar bands, cheek retractors, and disposables',
    productCount: 73,
    gradient: 'from-orange-50 to-orange-100',
    iconColor: 'text-orange-600',
    borderColor: 'border-orange-200',
    abbr: 'CN',
    image: "https://m.media-amazon.com/images/I/51CG3GGCqtL._AC_UF1000,1000_QL80_.jpg"
  },

  {
    id: 8,
    name: 'Health & Hygiene',
    slug: 'health-and-hygiene',
    description: 'Maks, gloves, sanitizers and much more',
    productCount: 15,
    gradient: 'from-orange-50 to-orange-100',
    iconColor: 'text-orange-600',
    borderColor: 'border-orange-200',
    abbr: 'CN',
    image: "https://encrypted-tbn0.gstatic.com/images?q=tbn:ANd9GcRsMxtcnzd7ggtAWYsznZszKwHWkenbPjdmXA&s"
  },
];

// export const products = [
//   // BRACKETS
//   {
//     id: 1,
//     name: '3M Unitek Gemini Metal Brackets',
//     slug: '3m-unitek-gemini-metal-brackets',
//     category: 'brackets',
//     price: "₹2,000/-",
//     sku: '3M-GEM-022-MBT',
//     stockStatus: 'in-stock',
//     specs: {
//       slotSize: '0.022"',
//       prescription: 'MBT',
//       material: 'Stainless Steel',
//       hooks: '3-4-5',
//       torqueAngulation: 'Standard MBT',
//     },
//     shortSpecs: '0.022" Slot | MBT | Stainless Steel',
//     description:
//       'The Gemini bracket system from 3M Unitek offers reliable performance and consistent finish. Ideal for standard MBT mechanics with excellent ligature tie-wing design.',
//     clinicalNotes:
//       'Suitable for full-bracket therapy. Rhomboidal base for enhanced bond strength. Works with standard MBT prescription protocols. Compatible with both 0.018" and 0.022" NiTi wires.',
//     packaging: '10 brackets per pack (upper and lower sets available)',
//     shippingInfo: 'Ships in 1-2 business days. Cold-chain not required.',
//     compatibility: 'Compatible with all standard 0.022" wires — NiTi, SS, and Beta-Ti',
//     tags: ['MBT', 'metal', 'brackets', '0.022'],
//     featured: true,
//     trending: true,
//     newArrival: false,
//     bestSeller: true,
//     gradient: 'from-blue-50 to-blue-100',
//     iconColor: 'text-blue-600',
//   },
//   {
//     id: 2,
//     name: 'Ormco Inspire ICE Ceramic Brackets',
//     slug: 'ormco-inspire-ice-ceramic-brackets',
//     category: 'brackets',
//     price: "₹2,000/-",
//     sku: 'ORM-ICE-022-MBT',
//     stockStatus: 'in-stock',
//     specs: {
//       slotSize: '0.022"',
//       prescription: 'MBT',
//       material: 'Monocrystalline Ceramic',
//       hooks: '3-4-5',
//       torqueAngulation: 'Standard MBT',
//     },
//     shortSpecs: '0.022" Slot | MBT | Monocrystalline Ceramic',
//     description:
//       'Inspire ICE is Ormco\'s clearest ceramic bracket, offering exceptional aesthetics with a translucent, non-staining monocrystalline ceramic body.',
//     clinicalNotes:
//       'Does not stain or discolor over time. Smooth tie-wing surface reduces friction. Ideal for aesthetic-conscious adult patients. Removal is clean and safe without enamel damage.',
//     packaging: 'Tray of 20 brackets (5 per quadrant)',
//     shippingInfo: 'Ships in 1-2 business days.',
//     compatibility: 'All standard 0.022" archwires — NiTi, SS',
//     tags: ['ceramic', 'aesthetic', 'MBT', '0.022', 'brackets'],
//     featured: true,
//     trending: false,
//     newArrival: false,
//     bestSeller: true,
//     gradient: 'from-blue-50 to-blue-100',
//     iconColor: 'text-blue-600',
//   },
//   {
//     id: 3,
//     name: 'Forestadent BioQuick SL Brackets',
//     slug: 'forestadent-bioquick-sl-brackets',
//     category: 'brackets',
//     price: "₹2,000/-",
//     sku: 'FOR-BQ-022-SL',
//     stockStatus: 'low-stock',
//     specs: {
//       slotSize: '0.022"',
//       prescription: 'MBT',
//       material: 'Stainless Steel',
//       type: 'Passive Self-Ligating',
//       hooks: '3-4-5',
//     },
//     shortSpecs: '0.022" Slot | Passive SL | MBT',
//     description:
//       'BioQuick is Forestadent\'s passive self-ligating bracket that reduces chair time and patient discomfort with low-friction, no-tie mechanics.',
//     clinicalNotes:
//       'Passive clip reduces initial friction allowing for efficient initial alignment. The wide open space allows easy wire insertion and removal. Ideal for full extraction and non-extraction cases.',
//     packaging: '20 brackets per pack',
//     shippingInfo: 'Ships in 2-3 business days.',
//     compatibility: 'All 0.022" round and rectangular wires.',
//     tags: ['self-ligating', 'SL', 'passive', 'brackets', 'MBT'],
//     featured: false,
//     trending: true,
//     newArrival: true,
//     bestSeller: false,
//     gradient: 'from-blue-50 to-blue-100',
//     iconColor: 'text-blue-600',
//   },
//   // WIRES
//   {
//     id: 4,
//     name: '3M Unitek TMA Rectangular Wire',
//     slug: '3m-unitek-tma-rectangular-wire',
//     category: 'wires-springs',
//     price: "₹2,000/-",
//     sku: '3M-TMA-016022',
//     stockStatus: 'in-stock',
//     specs: {
//       dimension: '0.016" x 0.022"',
//       material: 'Beta-Titanium (TMA)',
//       slot: '0.022"',
//       length: 'Upper & Lower arch',
//     },
//     shortSpecs: '0.016 x 0.022 | Beta-Ti | 0.022" Slot',
//     description:
//       'TMA (Titanium Molybdenum Alloy) wires offer a perfect blend of flexibility and springback. Ideal for torque control in the finishing stages.',
//     clinicalNotes:
//       'Half the stiffness of stainless steel — excellent for 3rd order (torque) mechanics. Use in the working and finishing stages. Cannot be heat-treated, but can be easily bent chairside.',
//     packaging: '10 wires per pack',
//     shippingInfo: 'Ships in 1-2 business days.',
//     compatibility: 'Use in 0.022" bracket systems only.',
//     tags: ['TMA', 'beta-titanium', 'rectangular', 'wire', '0.022'],
//     featured: true,
//     trending: false,
//     newArrival: false,
//     bestSeller: true,
//     gradient: 'from-slate-50 to-slate-100',
//     iconColor: 'text-slate-600',
//   },
//   {
//     id: 5,
//     name: 'Ormco Copper NiTi Wire',
//     slug: 'ormco-copper-niti-wire',
//     category: 'wires-springs',
//     price: "₹2,000/-",
//     sku: 'ORM-CUNITI-014',
//     stockStatus: 'in-stock',
//     specs: {
//       dimension: '0.014" Round',
//       material: 'Copper NiTi',
//       slot: '0.018" / 0.022"',
//       length: 'Upper & Lower arch',
//       activationTemp: '27°C (body temperature activated)',
//     },
//     shortSpecs: '0.014" Round | Copper NiTi | Body-temp Activated',
//     description:
//       'Ormco Copper NiTi activates at body temperature, providing gentle continuous forces ideal for initial alignment of crowded dentition.',
//     clinicalNotes:
//       'Delivers consistent, light, continuous forces. Excellent for the initial alignment stage. Activates with body heat — no hot water or heat required. Reduce patient discomfort significantly compared to SS initial wires.',
//     packaging: 'Pack of 10 wires',
//     shippingInfo: 'Ships in 1-2 business days.',
//     compatibility: 'Suitable for both 0.018" and 0.022" bracket systems.',
//     tags: ['copper', 'NiTi', 'nickel-titanium', 'wire', 'initial', 'round'],
//     featured: true,
//     trending: true,
//     newArrival: false,
//     bestSeller: true,
//     gradient: 'from-slate-50 to-slate-100',
//     iconColor: 'text-slate-600',
//   },
//   {
//     id: 6,
//     name: 'American Orthodontics SS Wire',
//     slug: 'american-orthodontics-ss-wire',
//     category: 'wires-springs',
//     price: "₹2,000/-",
//     sku: 'AO-SS-018R',
//     stockStatus: 'in-stock',
//     specs: {
//       dimension: '0.018" Round',
//       material: 'Stainless Steel',
//       slot: '0.018" / 0.022"',
//       length: 'Upper & Lower arch',
//     },
//     shortSpecs: '0.018" Round | Stainless Steel',
//     description:
//       'High-quality stainless steel round wire for leveling and alignment. Consistent cross-section and smooth surface for reliable sliding mechanics.',
//     clinicalNotes:
//       'Use after NiTi initial alignment. Provides rigidity for leveling. Can be bent and shaped. Good for space closure with frictionless mechanics.',
//     packaging: 'Pack of 10 wires',
//     shippingInfo: 'Ships same day for orders before 2 PM.',
//     compatibility: '0.018" and 0.022" bracket systems.',
//     tags: ['stainless-steel', 'SS', 'wire', 'round', '0.018'],
//     featured: false,
//     trending: false,
//     newArrival: false,
//     bestSeller: false,
//     gradient: 'from-slate-50 to-slate-100',
//     iconColor: 'text-slate-600',
//   },
//   // BUCCAL TUBES
//   {
//     id: 7,
//     name: '3M Unitek Victory Series Buccal Tube',
//     slug: '3m-unitek-victory-buccal-tube',
//     category: 'bands-tubes',
//     price: "₹2,000/-",
//     sku: '3M-VIC-BT-022-MBT',
//     stockStatus: 'in-stock',
//     specs: {
//       slotSize: '0.022"',
//       prescription: 'MBT',
//       type: 'Non-Convertible Monoblock',
//       molar: 'Upper & Lower First Molar',
//       material: 'Stainless Steel',
//     },
//     shortSpecs: '0.022" | MBT | Non-Convertible | First Molar',
//     description:
//       'Victory Series monoblock buccal tubes with reliable bond strength and superior bracket slot consistency. Industry standard for full-bracket therapy.',
//     clinicalNotes:
//       'Rhomboidal base ensures excellent bond strength and easy positioning. Integrated torque and angulation built into the base. Standard vertical slot for auxiliary wire.',
//     packaging: '10 tubes per pack (specify upper/lower, left/right)',
//     shippingInfo: 'Ships in 1-2 business days.',
//     compatibility: 'Standard 0.022" rectangular archwires.',
//     tags: ['buccal-tube', 'MBT', '0.022', 'first-molar', 'non-convertible'],
//     featured: true,
//     trending: false,
//     newArrival: false,
//     bestSeller: true,
//     gradient: 'from-indigo-50 to-indigo-100',
//     iconColor: 'text-indigo-600',
//   },
//   {
//     id: 8,
//     name: 'Ormco Titanium Orthos Buccal Tube',
//     slug: 'ormco-titanium-orthos-buccal-tube',
//     category: 'bands-tubes',
//     price: "₹2,000/-",
//     sku: 'ORM-TIO-022-MBT',
//     stockStatus: 'in-stock',
//     specs: {
//       slotSize: '0.022"',
//       prescription: 'MBT',
//       type: 'Non-Convertible',
//       material: 'Titanium',
//       molar: 'Upper & Lower First Molar',
//     },
//     shortSpecs: '0.022" | MBT | Titanium | Non-Convertible',
//     description:
//       'Titanium Orthos buccal tubes offer maximum corrosion resistance and biocompatibility. Ideal for patients with nickel sensitivity.',
//     clinicalNotes:
//       'Titanium construction makes these suitable for nickel-allergic patients. Maintains precision slot dimensions throughout treatment. Smooth outer surface for patient comfort.',
//     packaging: '10 tubes per pack',
//     shippingInfo: 'Ships in 2-3 business days.',
//     compatibility: 'All standard 0.022" archwires.',
//     tags: ['buccal-tube', 'titanium', 'MBT', '0.022', 'nickel-free'],
//     featured: false,
//     trending: true,
//     newArrival: false,
//     bestSeller: false,
//     gradient: 'from-indigo-50 to-indigo-100',
//     iconColor: 'text-indigo-600',
//   },
//   // ELASTICS
//   {
//     id: 9,
//     name: 'American Orthodontics Power Chain',
//     slug: 'american-orthodontics-power-chain',
//     category: 'elastics',
//     price: "₹2,000/-",
//     sku: 'AO-PC-CL-CLR',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Closed Link Power Chain',
//       color: 'Clear / Grey / Silver',
//       material: 'Medical-grade Polyurethane',
//       length: '15" spool',
//     },
//     shortSpecs: 'Closed Link | Clear | 15" Spool',
//     description:
//       'Medical-grade polyurethane power chain for space closure and maintaining alignment. Consistent force delivery with minimal creep.',
//     clinicalNotes:
//       'Use for space closure mechanics, diastema closure, and rotational correction. Clear option for anterior aesthetics. Forces decay over time — change every 4-6 weeks.',
//     packaging: '15" continuous spool — can be cut to desired length',
//     shippingInfo: 'Ships same day for orders before 2 PM.',
//     compatibility: 'All standard 0.018" and 0.022" bracket systems.',
//     tags: ['power-chain', 'elastics', 'space-closure', 'clear'],
//     featured: true,
//     trending: false,
//     newArrival: false,
//     bestSeller: true,
//     gradient: 'from-purple-50 to-purple-100',
//     iconColor: 'text-purple-600',
//   },
//   {
//     id: 10,
//     name: 'Ormco Latex Elastic Ligatures',
//     slug: 'ormco-latex-elastic-ligatures',
//     category: 'elastics',
//     price: "₹2,000/-",
//     sku: 'ORM-EL-CLR-1000',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Elastic Ligature Ties',
//       material: 'Latex',
//       color: 'Clear',
//       quantity: '1000 per bag',
//     },
//     shortSpecs: 'Elastic Ligatures | Clear | 1000/bag',
//     description:
//       'High-quality latex elastic ligatures for securing archwires to bracket tie-wings. Consistent diameter and elongation for reliable force.',
//     clinicalNotes:
//       'Standard elastic ties for routine bracket ligation. Clear option preferred for anterior segments. Replace at every appointment to maintain tie force.',
//     packaging: '1000 ties per bag — multiple color options available',
//     shippingInfo: 'Ships same day for orders before 2 PM.',
//     compatibility: 'All standard bracket systems.',
//     tags: ['ligature', 'elastic', 'ties', 'latex', 'clear'],
//     featured: false,
//     trending: false,
//     newArrival: false,
//     bestSeller: true,
//     gradient: 'from-purple-50 to-purple-100',
//     iconColor: 'text-purple-600',
//   },
//   {
//     id: 11,
//     name: 'Dentsply Ultra Power Chain',
//     slug: 'dentsply-ultra-power-chain',
//     category: 'elastics',
//     price: "₹2,000/-",
//     sku: 'DEN-UPC-SH-CLR',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Short-Link Power Chain',
//       material: 'Polyurethane',
//       color: 'Clear / Silver',
//       length: '15" spool',
//     },
//     shortSpecs: 'Short Link | Clear/Silver | 15" Spool',
//     description:
//       'Ultra Power Chain with short inter-link spacing for gentle yet continuous forces. Superior stain resistance and minimal force degradation.',
//     clinicalNotes:
//       'Short-link design provides more chain per unit length, useful for smaller spaces. Less visible in anterior region. Superior force consistency vs standard chains.',
//     packaging: '15" spool',
//     shippingInfo: 'Ships in 1-2 business days.',
//     compatibility: 'All 0.018" and 0.022" bracket systems.',
//     tags: ['power-chain', 'short-link', 'elastics', 'dentsply'],
//     featured: false,
//     trending: true,
//     newArrival: false,
//     bestSeller: false,
//     gradient: 'from-purple-50 to-purple-100',
//     iconColor: 'text-purple-600',
//   },
//   // ADHESIVES
//   {
//     id: 12,
//     name: '3M Unitek Transbond XT Adhesive',
//     slug: '3m-transbond-xt-adhesive',
//     category: 'adhesives',
//     price: "₹2,000/-",
//     sku: '3M-TXT-LCA',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Light Cure Adhesive',
//       cure: 'Light Cure (Visible Light)',
//       viscosity: 'Regular',
//       quantity: '5g syringe',
//     },
//     shortSpecs: 'Light Cure | 5g Syringe',
//     description:
//       'Industry-leading light-cure orthodontic adhesive for reliable bracket bonding. Optimal viscosity for precise bracket placement before curing.',
//     clinicalNotes:
//       'Standard 10-second cure per bracket. Excellent bond strength (>12 MPa). Radiopaque — visible on X-ray. Use with Transbond MIP or XT Primer for best results.',
//     packaging: '5g syringe with 50 dispensing tips',
//     shippingInfo: 'Ships with cold-pack. Order before 12 PM for same-day dispatch.',
//     compatibility: 'All bracket types — metal, ceramic, and self-ligating.',
//     tags: ['adhesive', 'bonding', 'light-cure', 'Transbond', '3M'],
//     featured: true,
//     trending: false,
//     newArrival: false,
//     bestSeller: true,
//     gradient: 'from-amber-50 to-amber-100',
//     iconColor: 'text-amber-600',
//   },
//   {
//     id: 13,
//     name: 'GC Ortho-Connect Flow',
//     slug: 'gc-ortho-connect-flow',
//     category: 'adhesives',
//     price: "₹2,000/-",
//     sku: 'GC-OCF-3g',
//     stockStatus: 'low-stock',
//     specs: {
//       type: 'Light Cure Flowable Adhesive',
//       cure: 'Visible Light',
//       viscosity: 'Flowable',
//       quantity: '3g',
//     },
//     shortSpecs: 'Light Cure Flowable | 3g',
//     description:
//       'Flowable orthodontic adhesive for bonding metal and ceramic brackets. High fluoride release for caries prevention during treatment.',
//     clinicalNotes:
//       'Fluoride release helps prevent enamel demineralization around bracket margins. Flowable viscosity allows for thin uniform bond layer. Excellent for patients at high caries risk.',
//     packaging: '3g syringe',
//     shippingInfo: 'Ships with cold-pack in 1-2 business days.',
//     compatibility: 'Metal and ceramic brackets.',
//     tags: ['adhesive', 'flowable', 'fluoride', 'GC', 'light-cure'],
//     featured: false,
//     trending: true,
//     newArrival: true,
//     bestSeller: false,
//     gradient: 'from-amber-50 to-amber-100',
//     iconColor: 'text-amber-600',
//   },
//   // PLIERS
//   {
//     id: 14,
//     name: 'Hu-Friedy Weingart Plier',
//     slug: 'hu-friedy-weingart-plier',
//     category: 'pliers',
//     price: "₹2,000/-",
//     sku: 'HF-WP-OT',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Weingart Plier',
//       material: 'High-Grade Stainless Steel',
//       tips: 'Smooth tapered tips',
//       use: 'Wire placement and adjustment',
//     },
//     shortSpecs: 'Weingart | SS | Smooth Tips',
//     description:
//       'Professional-grade Hu-Friedy Weingart plier for placing and removing archwires with minimal trauma. Ergonomic grip, autoclavable.',
//     clinicalNotes:
//       'Essential chairside plier for all archwire work. Smooth tips prevent wire surface damage. Balanced weight for precise control. Autoclavable at 134°C.',
//     packaging: 'Single instrument in sterile packaging',
//     shippingInfo: 'Ships in 1-2 business days.',
//     compatibility: 'All NiTi, SS, and Beta-Ti archwires.',
//     tags: ['plier', 'weingart', 'Hu-Friedy', 'wire'],
//     featured: true,
//     trending: false,
//     newArrival: false,
//     bestSeller: true,
//     gradient: 'from-zinc-50 to-zinc-100',
//     iconColor: 'text-zinc-600',
//   },
//   {
//     id: 15,
//     name: 'Ormco Bird Beak Plier',
//     slug: 'ormco-bird-beak-plier',
//     category: 'pliers',
//     price: "₹2,000/-",
//     sku: 'ORM-BBP-139',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Bird Beak Plier (No. 139)',
//       material: 'High-Carbon Stainless Steel',
//       tips: 'Round & square beaks',
//       use: 'Wire bending and loop formation',
//     },
//     shortSpecs: 'Bird Beak #139 | SS | Round+Square Tips',
//     description:
//       'Classic Bird Beak #139 plier for forming loops and bends in stainless steel and TMA wires. Round beak for forming, square beak for sharp angles.',
//     clinicalNotes:
//       'Used for forming vertical loops, T-loops, and closing loops in SS and TMA wires. Do not use on NiTi wires. Excellent for auxilary spring fabrication.',
//     packaging: 'Single instrument',
//     shippingInfo: 'Ships in 1-2 business days.',
//     compatibility: 'SS and Beta-Ti (TMA) wires only. NOT for NiTi.',
//     tags: ['plier', 'bird-beak', '139', 'wire-bending'],
//     featured: false,
//     trending: false,
//     newArrival: false,
//     bestSeller: false,
//     gradient: 'from-zinc-50 to-zinc-100',
//     iconColor: 'text-zinc-600',
//   },
//   {
//     id: 16,
//     name: 'American Orthodontics Ligature Cutter',
//     slug: 'ao-ligature-cutter',
//     category: 'pliers',
//     price: "₹2,000/-",
//     sku: 'AO-LC-SS',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Ligature Cutter',
//       material: 'Stainless Steel',
//       use: 'Cutting ligature wires and elastic ligatures',
//     },
//     shortSpecs: 'Ligature Cutter | SS | Multipurpose',
//     description:
//       'Precision ligature cutter for cleanly cutting stainless steel ligatures and elastic ties without wire distortion or patient discomfort.',
//     clinicalNotes:
//       'Keep sharp — replace or resharpen if cutting action becomes dull. Avoid using on archwires as this will damage the cutting edge. Clean and sterilize after each use.',
//     packaging: 'Single instrument',
//     shippingInfo: 'Ships in 1-2 business days.',
//     compatibility: 'SS ligature wires and elastic ties.',
//     tags: ['plier', 'cutter', 'ligature', 'AO'],
//     featured: false,
//     trending: false,
//     newArrival: false,
//     bestSeller: false,
//     gradient: 'from-zinc-50 to-zinc-100',
//     iconColor: 'text-zinc-600',
//   },
//   // INSTRUMENTS
//   {
//     id: 17,
//     name: 'Dentsply Separator Placing Plier',
//     slug: 'dentsply-separator-placing-plier',
//     category: 'instruments',
//     price: "₹2,000/-",
//     sku: 'DEN-SPP-1',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Molar Separator Plier',
//       material: 'Stainless Steel',
//       use: 'Placing elastomeric separators',
//     },
//     shortSpecs: 'Separator Plier | SS',
//     description:
//       'Essential instrument for placing elastomeric separators between molar contacts before banding. Ergonomic design for efficient placement.',
//     clinicalNotes:
//       'Place separator securely between contact area using a gentle figure-8 motion. Confirm separator is seated below the contact point. Patient should feel mild pressure — not pain.',
//     packaging: 'Single instrument',
//     shippingInfo: 'Ships in 1-2 business days.',
//     compatibility: 'All standard elastomeric separators.',
//     tags: ['instrument', 'separator', 'plier', 'banding'],
//     featured: false,
//     trending: false,
//     newArrival: false,
//     bestSeller: false,
//     gradient: 'from-teal-50 to-teal-100',
//     iconColor: 'text-teal-600',
//   },
//   // ALIGNER ACCESSORIES
//   {
//     id: 18,
//     name: 'Ormco Damon Aligner Chewies',
//     slug: 'ormco-damon-aligner-chewies',
//     category: 'aligner-accessories',
//     price: "₹2,000/-",
//     sku: 'ORM-CHW-CLR',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Aligner Seating Chewies',
//       material: 'Polyurethane Foam',
//       color: 'Clear / Multiple Colors',
//       quantity: '10 per pack',
//     },
//     shortSpecs: 'Aligner Chewies | Foam | 10/pack',
//     description:
//       'Soft foam chewies help patients seat aligners fully and evenly, ensuring complete engagement of all attachment points.',
//     clinicalNotes:
//       'Instruct patients to bite on chewie for 5-10 minutes after inserting each aligner tray. Helps seat aligners over attachments. Replace chewies monthly.',
//     packaging: 'Pack of 10 chewies',
//     shippingInfo: 'Ships same day.',
//     compatibility: 'All clear aligner systems — Invisalign, Ormco, etc.',
//     tags: ['aligner', 'chewie', 'clear-aligner', 'accessories'],
//     featured: false,
//     trending: true,
//     newArrival: false,
//     bestSeller: true,
//     gradient: 'from-sky-50 to-sky-100',
//     iconColor: 'text-sky-600',
//   },
//   // RETAINERS
//   {
//     id: 19,
//     name: 'American Orthodontics Hawley Retainer Kit',
//     slug: 'ao-hawley-retainer-kit',
//     brand: 'American Orthodontics',
//     brandSlug: 'american-orthodontics',
//     category: 'retainers',
//     price: "₹2,000/-",
//     sku: 'AO-HRK-FULL',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Hawley Retainer Components',
//       includes: 'Adam clasps, labial bow wire, acrylic plates',
//       material: 'Stainless Steel & Acrylic',
//     },
//     shortSpecs: 'Hawley Retainer Components | Full Kit',
//     description:
//       'Complete Hawley retainer fabrication kit with SS clasps, labial bows, and acrylic. Essential for lab-fabricated removable retainers.',
//     clinicalNotes:
//       'Standard Hawley retainer components for in-house or lab fabrication. Adam clasps for 1st premolars or 1st molars. Adjust labial bow to exact arch form post-debond.',
//     packaging: 'Full kit with clasps, bows, and instructions',
//     shippingInfo: 'Ships in 1-2 business days.',
//     compatibility: 'Standard Hawley retainer fabrication protocol.',
//     tags: ['retainer', 'Hawley', 'removable', 'post-treatment'],
//     featured: false,
//     trending: false,
//     newArrival: false,
//     bestSeller: false,
//     gradient: 'from-green-50 to-green-100',
//     iconColor: 'text-green-600',
//   },
//   // CONSUMABLES
//   {
//     id: 20,
//     name: 'Dentsply Elastomeric Separators',
//     slug: 'dentsply-elastomeric-separators',
//     brand: 'Dentsply Sirona',
//     brandSlug: 'dentsply-sirona',
//     category: 'consumables',
//     price: "₹2,000/-",
//     sku: 'DEN-SEP-1000',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Elastomeric Molar Separators',
//       material: 'Latex Elastomeric',
//       size: 'Standard',
//       quantity: '1000 per bag',
//     },
//     shortSpecs: 'Elastomeric Separators | Standard | 1000/bag',
//     description:
//       'Standard-size elastomeric molar separators for creating space before banding. Highly elastic, consistent diameter, easy to place.',
//     clinicalNotes:
//       'Place 1-2 weeks before banding appointment to allow adequate space creation. Check at banding appointment — remove if they fall out or cause excessive pain.',
//     packaging: 'Bag of 1000 separators',
//     shippingInfo: 'Ships same day.',
//     compatibility: 'Use with separator placing plier.',
//     tags: ['separator', 'elastomeric', 'banding', 'consumables'],
//     featured: false,
//     trending: false,
//     newArrival: false,
//     bestSeller: true,
//     gradient: 'from-orange-50 to-orange-100',
//     iconColor: 'text-orange-600',
//   },
//   {
//     id: 21,
//     name: 'Ortho Technology Cheek Retractors',
//     slug: 'ortho-technology-cheek-retractors',
//     brand: 'Ortho Technology',
//     brandSlug: 'ortho-technology',
//     category: 'consumables',
//     price: "₹2,000/-",
//     sku: 'OT-CR-DISP-50',
//     stockStatus: 'in-stock',
//     specs: {
//       type: 'Disposable Cheek Retractors',
//       material: 'Medical-grade Plastic',
//       size: 'Adult & Child (available)',
//       quantity: '50 per pack',
//     },
//     shortSpecs: 'Disposable Cheek Retractors | 50/pack',
//     description:
//       'Clear disposable cheek retractors for unobstructed access during bonding, photography, and intraoral procedures.',
//     clinicalNotes:
//       'Single-use — dispose after each patient. Provides excellent field access for bonding procedures, intraoral photography, and anterior composite work.',
//     packaging: 'Pack of 50',
//     shippingInfo: 'Ships same day.',
//     compatibility: 'Universal fit — adult and child sizes available.',
//     tags: ['cheek-retractor', 'disposable', 'consumables', 'bonding'],
//     featured: false,
//     trending: false,
//     newArrival: false,
//     bestSeller: false,
//     gradient: 'from-orange-50 to-orange-100',
//     iconColor: 'text-orange-600',
//   },
// ];

export function getCategoryBySlug(slug) {
  return categories.find((c) => c.slug === slug) || null;
}

export function getProductsByCategory(categorySlug) {
  return products.filter((p) => p.category === categorySlug);
}

export function getProductBySlug(slug) {
  return products.find((p) => p.slug === slug) || null;
}

export function getRelatedProducts(product, limit = 4) {
  return products
    .filter((p) => p.category === product.category && p.id !== product.id)
    .slice(0, limit);
}

export function getFeaturedProducts(tag, limit = 6) {
  let filtered = products;
  if (tag === 'bestSeller') filtered = products.filter((p) => p.bestSeller);
  else if (tag === 'trending') filtered = products.filter((p) => p.trending);
  else if (tag === 'newArrival') filtered = products.filter((p) => p.newArrival);
  else if (tag === 'featured') filtered = products.filter((p) => p.featured);
  return filtered.slice(0, limit);
}

export function getProductsByBrand(brandSlug, limit = 6) {
  return products.filter((p) => p.brandSlug === brandSlug).slice(0, limit);
}
