export const products = [
  {
    id: 1,
    name: "Ligature Director Double Ended plier curved",
    slug: "ligature-director-double-ended-plier-curved",
    category: "pliers",
    price: "₹1,200/-",
    sku: "LIGATURE DIRECTOR DOUBLE ENDED",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A double-ended hand instrument used to guide, tuck, and position ligature wires or elastic modules securely around bracket wings. The curved tip allows access to posterior teeth with greater ease.",
    clinicalNotes: "After an archwire is seated, the pointed working end is used to tuck the twisted tail of a wire ligature under the archwire or push an elastic module into place. The double-ended design provides two tip configurations in one instrument, reducing the need to switch tools chairside.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Essential at every adjustment appointment. Used for both stainless steel ligature wire placement and elastomeric module positioning. The curved version is especially useful for lower posterior brackets where access is limited.",
    tags: [
      "ligature",
      "director",
      "double",
      "ended",
      "plier",
      "curved"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1726158387509WhatsApp Image 2024-09-12 at 7.55.11 PM 1.png"
  },
  {
    id: 2,
    name: "Ligature Director Scaler",
    slug: "ligature-director-scaler",
    category: "pliers",
    price: "₹1,200/-",
    sku: "LIGATURE-DIRECTOR-SCALER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A combination instrument featuring a ligature director on one end and a scaler tip on the other.",
    clinicalNotes: "The ligature director end tucks wire ligatures under the archwire; the scaler end can remove plaque, calculus, or adhesive debris from bracket bases and archwire slots during treatment.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "A practical dual-purpose instrument for orthodontic adjustment appointments, reducing tray setup and saving chairside time.",
    tags: [
      "ligature",
      "director",
      "scaler",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1726158796044WhatsApp Image 2024-09-12 at 7.55.40 PM 1.png"
  },
  {
    id: 3,
    name: "Face Masks",
    slug: "face-masks",
    category: "health-and-hygiene",
    price: "₹10/-",
    sku: "FACE-MASKS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Disposable 3-ply protective face masks providing filtration of airborne particles, dust, and aerosols.",
    clinicalNotes: "Standard personal protective equipment for all dental and orthodontic procedures. Protects both clinician and patient from cross-contamination. Suitable for daily clinical wear throughout the working day.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "",
    tags: [
      "face",
      "masks",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1727960502878pink-color-n95-face-mask.jpg"
  },
  {
    id: 4,
    name: "Plier Stand",
    slug: "plier-stand",
    category: "miscellaneous",
    price: "₹800/-",
    sku: "PLIER-STAND",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A countertop stand designed to hold and organize multiple orthodontic pliers in an upright, accessible position.",
    clinicalNotes: "Keeps the working area organized and hygienic. Prevents instrument damage from being stacked or dropped, and allows the clinician to quickly identify and reach any plier during a procedure.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "",
    tags: [
      "plier",
      "stand",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1727960693334image 29.png"
  },
  {
    id: 5,
    name: "Ortho Wax",
    slug: "ortho-wax",
    category: "miscellaneous",
    price: "₹50/-",
    sku: "ORTHO-WAX",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A non-toxic, unscented dental wax used by patients at home to relieve soft tissue irritation from brackets, wires, or appliance edges.",
    clinicalNotes: "The patient rolls a small piece of wax between their fingers to soften it, then presses it over the irritating bracket or wire. The wax forms a smooth barrier between the metal and the cheek or lip.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Dispensed to patients at bonding and adjustment appointments. Safe if accidentally swallowed. Patients are instructed to remove it before brushing teeth.",
    tags: [
      "ortho",
      "wax",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1727960950654ortho_wax.jpg"
  },
  {
    id: 6,
    name: "Separators Blue (pkt of 1000)",
    slug: "separators-blue-pkt-of-1000",
    category: "elastics",
    price: "₹900/-",
    sku: "SEPARATORS-BLUE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Small elastomeric rings placed between molar contact points to create a gap before band placement.",
    clinicalNotes: "The separator is stretched with a separator plier and snapped into the interproximal contact area. Over 5–7 days, the separator gently pushes the teeth apart, creating just enough space to slide a molar band through the contact.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used at a pre-banding appointment. Without separators, band placement is impossible as the molar contact is too tight. Available in blue for easy visual identification.",
    tags: [
      "seprators",
      "blue",
      "pkt",
      "1000",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1727963927129WhatsApp Image 2024-10-03 at 7.20.47 PM.jpeg"
  },
  {
    id: 7,
    name: "Australian Wire Spool (Special Plus)",
    slug: "australian-wire-spool-special-plus",
    category: "wires-springs",
    price: "₹1,700/-",
    sku: "AUSTRALIAN-WIRE-SPOOL-SPECIAL-PLUS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A 25-foot spool of AJ Wilcock Special Plus (yellow label) Australian wire — a heat-treated stainless steel alloy developed specifically for orthodontic use. Properties: Australian wire is highly resilient, springy, and can be shaped and bent without permanently deforming. It maintains working forces over longer periods than standard stainless steel and has excellent formability for auxiliary spring fabrication.",
    clinicalNotes: "The classic wire for fabricating finger springs, loop archwires, and auxiliary appliances. Widely used in Begg and tip-edge techniques. The Special Plus grade is the most versatile and commonly prescribed grade.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "",
    tags: [
      "australian",
      "wire",
      "spool",
      "special",
      "plus",
      "wires"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1727964234449WhatsApp Image 2024-10-03 at 7.15.11 PM.jpeg"
  },
  {
    id: 8,
    name: "NiTi Wire Spool",
    slug: "niti-wire-spool",
    category: "wires-springs",
    price: "₹600/-",
    sku: "NITI-WIRE-SPOOL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A spool of nickel-titanium (NiTi) round archwire used in early stages of orthodontic treatment. Properties: NiTi wire has exceptional springback (shape memory), allowing it to generate light, continuous forces over a wide range of deflection. It returns to its original arch form even when severely displaced by a crowded tooth.",
    clinicalNotes: "The standard first archwire in most cases. Used during the leveling and alignment phase. The continuous gentle forces move teeth efficiently with less patient discomfort compared to stainless steel.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "",
    tags: [
      "niti",
      "wire",
      "spool",
      "wires",
      "and",
      "springs"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1727964462392WhatsApp Image 2024-10-03 at 7.19.02 PM.jpeg"
  },
  {
    id: 9,
    name: "TMA Wire Straight",
    slug: "tma-wire-straight",
    category: "wires-springs",
    price: "₹800/-",
    sku: "TMA-WIRE-STRAIGHT",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Beta-titanium (TMA — Titanium Molybdenum Alloy) straight archwire sticks, 7 inches long, packed 10 per packet. Properties: TMA wire has a stiffness roughly halfway between NiTi and stainless steel, combined with excellent formability. It can be bent and shaped like stainless steel while still delivering lower, more biologically favorable forces. It is also weldable.",
    clinicalNotes: "Used in the finishing stages of treatment where precise tooth positioning is required. TMA's combination of flexibility and formability makes it ideal for closing loops, torquing auxiliaries, and three-dimensional finishing bends that cannot be placed in stiffer stainless steel.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "",
    tags: [
      "tma",
      "wire",
      "straight",
      "wires",
      "and",
      "springs"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1727964896028WhatsApp Image 2024-10-03 at 7.22.57 PM.jpeg"
  },
  {
    id: 10,
    name: "Soldering Twizer",
    slug: "soldering-twizer",
    category: "pliers",
    price: "₹800/-",
    sku: "SOLDERING-TWIZER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Fine-tipped precision tweezers made from high-grade surgical steel, designed for use during laboratory soldering procedures.",
    clinicalNotes: "Used to hold and position small orthodontic components — such as hooks, cleats, and wire sections — during soldering or welding on molar bands and retainers.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Standard lab instrument for fabricating fixed appliances, lingual arches, and habit-breaking appliances.",
    tags: [
      "soldering",
      "twizer",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994514027IMG_4203.jpeg"
  },
  {
    id: 11,
    name: "Gracy Curette (set of 8)",
    slug: "gracy-curette-set-of-8",
    category: "pliers",
    price: "₹2,000/-",
    sku: "GRACY-CURETTE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A set of double-ended periodontal curettes with area-specific blade angulations for scaling and root planing.",
    clinicalNotes: "Inserted subgingivally to remove calculus and debris from root surfaces. Each curette in the set corresponds to specific teeth and surfaces (anterior, posterior, mesial, distal).",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Frequently used in orthodontic practices to manage periodontal health before, during, and after orthodontic treatment, particularly in adult patients or cases requiring multidisciplinary care.",
    tags: [
      "gracy",
      "curette",
      "set",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994534626IMG_4200.jpeg"
  },
  {
    id: 12,
    name: "Distal End Bender",
    slug: "distal-end-bender",
    category: "pliers",
    price: "₹1,200/-",
    sku: "DISTAL-END-BENDER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A plier designed to bend the distal end of an archwire at a precise angle immediately after it exits the last molar tube.",
    clinicalNotes: "After inserting the archwire, the tip of this plier grips the distal wire end and bends it downward (cinch-back), preventing the wire from sliding laterally or poking into the cheek mucosa.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used routinely at the end of every wire placement appointment. The cinch-back prevents patient discomfort and reduces wire migration.",
    tags: [
      "distal",
      "end",
      "bender",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994557968IMG_4199.jpeg"
  },
  {
    id: 13,
    name: "Ligature Director(double ended)",
    slug: "ligature-director-double-ended",
    category: "pliers",
    price: "₹1,200/-",
    sku: "LIGATURE-DIRECTER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A double-ended hand instrument used to guide, tuck, and position ligature wires or elastic modules securely around bracket wings. The curved tip allows access to posterior teeth with greater ease.",
    clinicalNotes: "After an archwire is seated, the pointed working end is used to tuck the twisted tail of a wire ligature under the archwire or push an elastic module into place. The double-ended design provides two tip configurations in one instrument, reducing the need to switch tools chairside.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Essential at every adjustment appointment. Used for both stainless steel ligature wire placement and elastomeric module positioning. The curved version is especially useful for lower posterior brackets where access is limited.",
    tags: [
      "ligature",
      "directer",
      "double",
      "ended",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994601534IMG_4198.jpeg"
  },
  {
    id: 14,
    name: "Band Seater",
    slug: "band-seater",
    category: "pliers",
    price: "₹400/-",
    sku: "BAND-SEATER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A hard acrylic or nylon bite stick used to assist in fully seating molar bands onto teeth.",
    clinicalNotes: "After the band is pushed to approximately its final position, the patient bites down firmly on the bite stick, which distributes occlusal force evenly over the band, driving it fully to its correct cervical position.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used at every banding appointment. Patient biting force is the most effective way to fully seat a molar band without causing pain. The bite stick transfers and distributes this force safely.",
    tags: [
      "band",
      "seater",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994666201IMG_4197.jpeg"
  },
  {
    id: 15,
    name: "Distal End Cutter (long handle with safety hold)",
    slug: "distal-end-cutter-long-handle-with-safety-hold",
    category: "pliers",
    price: "₹5,500/-",
    sku: "DISTAL-END-CUTTER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A precision cutting instrument with a long handle for leverage and a safety mechanism that retains the cut wire fragment inside the beak, preventing accidental ingestion or aspiration.",
    clinicalNotes: "Positioned at the distal edge of the last buccal tube, the cutter shears the excess archwire flush or slightly beyond the tube. The safety hold grabs the cut piece so it doesn't fly free.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Critical safety instrument used at every wire placement. The long handle version provides greater intraoral reach and cutting force, especially for heavier stainless steel or TMA wires.",
    tags: [
      "distal",
      "end",
      "cutter",
      "long",
      "handle",
      "with"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994786742IMG_4195.jpeg"
  },
  {
    id: 16,
    name: "How Plier Straight",
    slug: "how-plier-straight",
    category: "pliers",
    price: "₹1,500/-",
    sku: "HOW-PLIER-STRAIGHT",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A straight utility plier with serrated, rounded beaks — one flat and one round — designed for archwire manipulation.",
    clinicalNotes: "Used to insert and remove archwires, check for loose bands, and make minor wire adjustments. The serrated beaks provide a firm, non-slip grip on the wire without crushing it.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "One of the most versatile pliers in orthodontics. Used at virtually every appointment for wire insertion, wire manipulation, and band checking. Also referred to as a Howe plier.",
    tags: [
      "how",
      "plier",
      "straight",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994811265IMG_4194.jpeg"
  },
  {
    id: 17,
    name: "Bracket Placing Twizer",
    slug: "bracket-placing-twizer",
    category: "pliers",
    price: "₹800/-",
    sku: "BRACKET-PLACING-TWIZER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A fine-tipped tweezer with a locking or spring mechanism designed specifically for picking up and accurately placing metal or ceramic brackets onto tooth surfaces.",
    clinicalNotes: "The tip grips the bracket wings firmly, allowing the clinician to position the bracket precisely on the bonding agent applied to the tooth surface before curing. The spring release allows clean placement without disturbing the bracket position.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used at every bonding appointment. Accurate bracket placement directly determines the quality of tooth movement throughout treatment.",
    tags: [
      "bracket",
      "placing",
      "twizer",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994832159IMG_4193.jpeg"
  },
  {
    id: 18,
    name: "De-Bonding Plier",
    slug: "de-bonding-plier",
    category: "pliers",
    price: "₹1,500/-",
    sku: "DE-BONDING-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A specialized plier with shaped beaks designed to remove bonded orthodontic brackets from tooth enamel without fracturing the bracket or damaging the tooth surface.",
    clinicalNotes: "The beaks are placed at the base of the bracket wings, applying a controlled, shearing force that breaks the adhesive bond. The bracket comes free cleanly in most cases.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used at debonding (end of treatment) appointments. Proper technique with this plier minimizes enamel damage and fracture risk.",
    tags: [
      "de-bonding",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994853499IMG_4192.jpeg"
  },
  {
    id: 19,
    name: "MBT Gauge",
    slug: "mbt-gauge",
    category: "pliers",
    price: "₹1,200/-",
    sku: "MBT-GUAGE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A precise measuring gauge used to verify bracket placement height on the clinical crown of each tooth.",
    clinicalNotes: "Placed against the tooth surface, the gauge measures the distance from the bracket center to the incisal edge or cusp tip, ensuring all brackets are positioned at the correct height for each tooth type.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Essential for accurate indirect or direct bonding. Correct bracket height ensures proper torque, angulation, and in-out expression throughout treatment. The aluminium version offers a lightweight feel with the same accuracy.",
    tags: [
      "mbt",
      "gauge",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994880415IMG_4191.jpeg"
  },
  {
    id: 20,
    name: "Band Removing Plier",
    slug: "band-removing-plier",
    category: "pliers",
    price: "₹1,500/-",
    sku: "BAND-REMOVING-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A plier with a nylon-tipped beak that protects the tooth enamel, designed to remove cemented molar bands safely.",
    clinicalNotes: "The nylon tip is placed on the occlusal surface of the band while the metal beak engages the gingival margin. A squeezing motion breaks the cement seal and lifts the band off the tooth.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used at debonding appointments or whenever a band needs to be repositioned or replaced. The nylon tip prevents enamel fracture during removal.",
    tags: [
      "band",
      "removing",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994922953IMG_4188.jpeg"
  },
  {
    id: 21,
    name: "Mathew Plier (with ring)",
    slug: "mathew-plier-with-ring",
    category: "pliers",
    price: "₹1,900/-",
    sku: "MATHEW-PLIER-WITH-RING",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A locking ligature-tying plier with a spring-loaded handle and a sliding ring to lock the beaks in a closed position. Used primarily for tying wire ligatures.",
    clinicalNotes: "The beaks grasp the wire ligature end and twist it into a tight pigtail around the bracket. The locking ring holds the plier closed during twisting, preventing hand fatigue and maintaining consistent tension.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "A preferred instrument for wire ligation in practices using conventional brackets. Produces neat, consistently tight ligature ties.",
    tags: [
      "mathew",
      "plier",
      "with",
      "ring",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994949454IMG_4187.jpeg"
  },
  {
    id: 22,
    name: "MBT Gauge Aluminium",
    slug: "mbt-gauge-aluminium",
    category: "pliers",
    price: "₹2,400/-",
    sku: "MBT-GAUGE-ALUMINIUM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A precise measuring gauge used to verify bracket placement height on the clinical crown of each tooth.",
    clinicalNotes: "Placed against the tooth surface, the gauge measures the distance from the bracket center to the incisal edge or cusp tip, ensuring all brackets are positioned at the correct height for each tooth type.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Essential for accurate indirect or direct bonding. Correct bracket height ensures proper torque, angulation, and in-out expression throughout treatment. The aluminium version offers a lightweight feel with the same accuracy.",
    tags: [
      "mbt",
      "gauge",
      "aluminium",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995003279IMG_4185.jpeg"
  },
  {
    id: 23,
    name: "Band Pusher",
    slug: "band-pusher",
    category: "pliers",
    price: "₹700/-",
    sku: "BAND-PUSHER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A single-ended instrument with a flat, angled working tip used to push and adapt molar bands to the tooth surface.",
    clinicalNotes: "After placing the band on the tooth, the working tip is used to adapt and contour the band margins interproximally and gingivally to ensure proper fit before cementation.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used at every molar banding appointment alongside the band seater. Proper band adaptation ensures a good cement seal and stable anchorage unit.",
    tags: [
      "band",
      "pusher",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995031981IMG_4184.jpeg"
  },
  {
    id: 24,
    name: "Band Cutting Scissors",
    slug: "band-cutting-scissors",
    category: "pliers",
    price: "₹800/-",
    sku: "BAND-CUTTING-SCISSORS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Small, sharp scissors with fine blades designed for intraoral use in cutting elastic chains, ligature ties, and soft orthodontic materials.",
    clinicalNotes: "Used to trim excess elastic chain links, cut power chain to the correct length, or trim elastic modules. The fine blades allow precise cutting in tight intraoral spaces.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Standard chairside instrument at adjustment appointments. Also used to trim retainer material or auxiliary elastics when needed.",
    tags: [
      "band",
      "cutting",
      "scissors",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995086623IMG_4183.jpeg"
  },
  {
    id: 25,
    name: "Light Wire Plier",
    slug: "light-wire-plier",
    category: "pliers",
    price: "₹1,500/-",
    sku: "LIGHT-WIRE-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A plier designed for bending and forming light-gauge orthodontic wires (typically round NiTi or stainless steel wires in the 0.012–0.018 range)",
    clinicalNotes: "The tapered beaks allow the clinician to create precise bends, loops, and curves in light archwires for early treatment mechanics such as leveling and alignment.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used primarily in early to mid-treatment stages when light flexible wires are in use. Essential for placing first, second, and third order bends in archwires.",
    tags: [
      "light",
      "wire",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995121028IMG_4182.jpeg"
  },
  {
    id: 26,
    name: "Heavy Wire Cutter",
    slug: "heavy-wire-cutter",
    category: "pliers",
    price: "₹2,000/-",
    sku: "HEAVY-WIRE-CUTTER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A robust cutter with hardened, carbide-tipped blades designed to cut heavy-gauge stainless steel and rectangular archwires.",
    clinicalNotes: "Positioned over the wire at the desired cut point, a firm closing action shears cleanly through the wire. Carbide tips maintain their edge even with repeated use on hard wire alloys.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used for cutting stainless steel, TMA, and other heavy-gauge archwires during treatment progression. A heavier build than standard ligature cutters is required for these materials.",
    tags: [
      "heavy",
      "wire",
      "cutter",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995150116IMG_4181.jpeg"
  },
  {
    id: 27,
    name: "Crimpable Hooks Plier",
    slug: "crimpable-hooks-plier",
    category: "pliers",
    price: "₹2,400/-",
    sku: "CRIMPABLE-HOOKS-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A plier with specially shaped beaks designed to compress and lock crimpable hooks onto archwires.",
    clinicalNotes: "A crimpable hook is threaded onto the archwire at the desired location, then the plier is used to crimp (compress) the hook's barrel section firmly onto the wire, securing it in place without soldering.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used when additional hooks are needed for elastic attachment mid-wire. Particularly useful in extraction cases where Class II or Class III elastics are required but no bracket hook is available at the ideal location.",
    tags: [
      "crimpable",
      "hooks",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995183539IMG_4180.jpeg"
  },
  {
    id: 28,
    name: "Ligature Wire Cutter",
    slug: "ligature-wire-cutter",
    category: "pliers",
    price: "₹5,000/-",
    sku: "LIGATURE-WIRE-CUTTER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A fine-tipped cutter specifically designed for cutting thin stainless steel ligature wires flush with the bracket wing.",
    clinicalNotes: "After a wire ligature is tied and twisted, the excess pigtail is cut as short as possible using this cutter. The fine tip allows close, flush cuts to prevent the wire end from irritating soft tissue.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used at every adjustment appointment where wire ligation is performed. The slim profile allows access between brackets in crowded areas.",
    tags: [
      "ligature",
      "wire",
      "cutter",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995217108IMG_4179.jpeg"
  },
  {
    id: 29,
    name: "Hard Wire Cutter",
    slug: "hard-wire-cutter",
    category: "pliers",
    price: "₹5,000/-",
    sku: "HARD-WIRE-CUTTER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A heavy-duty wire cutter with reinforced cutting edges, designed for cutting hard, thick, or multi-strand orthodontic wires.",
    clinicalNotes: "Applied over the wire with steady, controlled pressure to make a clean cut. The reinforced blades prevent deformation and maintain accuracy.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Suitable for cutting coaxial wire, heavy stainless steel archwires, or any material that would dull or damage lighter cutters. A necessary instrument in any orthodontic practice handling full-range wire sequences.",
    tags: [
      "hard",
      "wire",
      "cutter",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995251702IMG_4178.jpeg"
  },
  {
    id: 30,
    name: "Weingart Plier",
    slug: "weingart-plier",
    category: "pliers",
    price: "₹2,200/-",
    sku: "WEINGART-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "One of the most commonly used pliers in orthodontics, with slim tapered beaks ideal for inserting archwires into bracket slots and buccal tubes.",
    clinicalNotes: "The narrow, angled tips slide beneath and around archwires to guide them into bracket slots from anterior to posterior. Also used to pull archwires out during adjustment.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Standard instrument at every wire change appointment. Particularly essential when heavier, stiffer archwires need to be threaded into place. Also used for placing auxiliary springs and closing loops.",
    tags: [
      "weingart",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995280032IMG_4177.jpeg"
  },
  {
    id: 31,
    name: "Ligature Forming Plier",
    slug: "ligature-forming-plier",
    category: "pliers",
    price: "₹2,500/-",
    sku: "LIGATURE-FORMING-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A plier used to pre-form wire ligatures into precise shapes (typically a loop or hairpin) before tying them to brackets.",
    clinicalNotes: "A length of ligature wire is placed in the plier's working notch, and a bending motion creates a consistent pre-formed tie. The pre-formed ligatures can then be placed quickly and uniformly across all brackets.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Useful in practices that prefer wire ligation for its superior force control compared to elastomeric modules.",
    tags: [
      "ligature",
      "forming",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995305007IMG_4176.jpeg"
  },
  {
    id: 32,
    name: "Band Crimping Plier",
    slug: "band-crimping-plier",
    category: "pliers",
    price: "₹1,600/-",
    sku: "BAND-CRIMPING-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A plier designed to crimp (compress and tighten) the margins of molar bands to improve their fit and adaptation to the tooth contour.",
    clinicalNotes: "After placing the band on the tooth model or clinically, the crimping beaks are applied at the band margins to slightly constrict the band and improve its cervical seal before or after cementation.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Helps prevent band loosening and cement washout during treatment by ensuring a well-adapted fit.",
    tags: [
      "band",
      "crimping",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995339272IMG_4175.jpeg"
  },
  {
    id: 33,
    name: "Buccal tube Placing Twizer",
    slug: "buccal-tube-placing-twizer",
    category: "pliers",
    price: "₹900/-",
    sku: "BUCCAL-TUBE-PLACING-TWIZER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A tweezer with slightly angulated tips optimized for picking up and placing buccal tubes onto molar tooth surfaces during bonding.",
    clinicalNotes: "The tweezer grips the buccal tube by its base, allowing precise positioning on the molar surface at the correct height and angulation before light-curing the adhesive.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used at bonding appointments as an alternative to welded buccal tubes on bands. Bondable buccal tubes are increasingly preferred as they eliminate the banding step entirely.",
    tags: [
      "buccal",
      "tube",
      "placing",
      "twizer",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995362129IMG_4173.jpeg"
  },
  {
    id: 34,
    name: "Lingual Buttons",
    slug: "lingual-buttons",
    category: "miscellaneous",
    price: "₹1,000/-",
    sku: "LINGUAL-BUTTONS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Lingual ButtoSmall, low-profile attachments bonded to the lingual (tongue-facing) surface of teeth.",
    clinicalNotes: "Elastic chains, coil springs, or ligature wires are attached to lingual buttons to apply tooth-moving forces that are not visible from the front. Ceramic lingual buttons blend with tooth color, minimizing their appearance even when visible. Metal lingual buttons offer maximum strength for heavier mechanics.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used for rotating teeth, correcting crossbites, or applying lingual forces as part of complex mechanics. Often used in combination with buccal brackets and auxiliaries.",
    tags: [
      "lingual",
      "buttons",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737996377484IMG_4111.jpeg"
  },
  {
    id: 35,
    name: "Lingual Buttons Metal",
    slug: "lingual-buttons-metal",
    category: "miscellaneous",
    price: "₹300/-",
    sku: "LINGUAL-BUTTONS-METAL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Lingual ButtoSmall, low-profile attachments bonded to the lingual (tongue-facing) surface of teeth.",
    clinicalNotes: "Elastic chains, coil springs, or ligature wires are attached to lingual buttons to apply tooth-moving forces that are not visible from the front. Ceramic lingual buttons blend with tooth color, minimizing their appearance even when visible. Metal lingual buttons offer maximum strength for heavier mechanics.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used for rotating teeth, correcting crossbites, or applying lingual forces as part of complex mechanics. Often used in combination with buccal brackets and auxiliaries.",
    tags: [
      "lingual",
      "buttons",
      "metal",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737996440881IMG_4122.jpeg"
  },
  {
    id: 36,
    name: "022 MBT Kit Galaxy",
    slug: "022-mbt-kit-galaxy",
    category: "brackets",
    price: "₹400/-",
    sku: "GALAXY",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "An economy-grade standard metal bracket kit using the MBT (McLaughlin, Bennett, Trevisi) prescription in a 0.022\" slot size.",
    clinicalNotes: "The MBT prescription is a widely used pre-adjusted edgewise bracket system that incorporates specific tip, torque, and in-out values for each tooth, reducing the need for wire bending in routine cases.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Suitable for standard fixed orthodontic treatment. The Galaxy kit is an excellent entry-level option for clinicians looking for reliable bracket prescriptions at an accessible price point.",
    tags: [
      "022",
      "mbt",
      "kit",
      "galaxy",
      "brackets"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737996898446IMG_4115.jpeg"
  },
  {
    id: 37,
    name: "022 MBT Self Ligating Ceramic Kit Premium",
    slug: "022-mbt-self-ligating-ceramic-kit-premium",
    category: "brackets",
    price: "₹11,000/-",
    sku: "SELF-LIGATING-CERAMIC-PREMIUM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "The premium version of a self-ligating ceramic bracket — combining the aesthetic advantage of tooth-colored ceramic with the mechanical advantage of self-ligation.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "For patients who want the most discreet, modern fixed appliance available. Represents the top tier of fixed orthodontic aesthetics combined with efficient mechanics.",
    tags: [
      "022",
      "mbt",
      "self",
      "ligating",
      "ceramic",
      "kit"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737997363627IMG_4113.jpeg"
  },
  {
    id: 38,
    name: "022 MBT Ceramic Kit Premium",
    slug: "022-mbt-ceramic-kit-premium",
    category: "brackets",
    price: "₹2,000/-",
    sku: "CERAMIC-KIT-PREMIUM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Ceramic (tooth-colored) bracket kits in the MBT 0.022\" prescription. The Premium version uses higher-grade ceramic with improved tie-wing strength and surface finish.",
    clinicalNotes: "Ceramic brackets blend with natural tooth color, making them far less visible than metal brackets. They function identically to metal MBT brackets, expressing the same prescription values.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "The preferred aesthetic option for adult patients and self-conscious adolescents. The Premium grade is recommended for cases requiring longer treatment duration or more demanding mechanics where bracket durability is important.",
    tags: [
      "022",
      "mbt",
      "ceramic",
      "kit",
      "premium",
      "brackets"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737997438140IMG_4098.jpeg"
  },
  {
    id: 39,
    name: "022 MBT Self Ligating Kit",
    slug: "022-mbt-self-ligating-kit",
    category: "brackets",
    price: "₹3,500/-",
    sku: "SELF-LIGATING-KIT",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A self-ligating metal bracket kit in the MBT 0.022\" prescription. Self-ligating brackets use a sliding clip or door mechanism to hold the archwire instead of elastic modules.",
    clinicalNotes: "Self-ligating brackets reduce friction on the archwire, can shorten appointment times (no module changes), and are generally associated with lower force levels during early treatment.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used in full fixed appliance treatment. Particularly favored in cases involving significant crowding where low-friction early alignment is beneficial.",
    tags: [
      "022",
      "mbt",
      "self",
      "ligating",
      "kit",
      "brackets"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737997535054IMG_4106.jpeg"
  },
  {
    id: 40,
    name: "022 MBT Ceramic Kit Clear",
    slug: "022-mbt-ceramic-kit-clear",
    category: "brackets",
    price: "₹2,600/-",
    sku: "CERAMIC-KIT-CLEAR",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A fully clear (highly translucent) ceramic bracket kit in the MBT prescription. Made from monocrystalline or highly refined polycrystalline alumina for maximum aesthetic transparency.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Ideal for patients with the highest aesthetic demands. The clear brackets are nearly invisible when bonded, making them the most discreet option among conventional fixed appliances.",
    tags: [
      "022",
      "mbt",
      "ceramic",
      "kit",
      "clear",
      "brackets"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737997604210IMG_4100.jpeg"
  },
  {
    id: 41,
    name: "022 MBT Ceramic Kit Economy",
    slug: "022-mbt-ceramic-kit-economy",
    category: "brackets",
    price: "₹900/-",
    sku: "CERAMIC-KIT-ECONOMY",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Ceramic (tooth-colored) bracket kits in the MBT 0.022\" prescription. The Premium version uses higher-grade ceramic with improved tie-wing strength and surface finish.",
    clinicalNotes: "Ceramic brackets blend with natural tooth color, making them far less visible than metal brackets. They function identically to metal MBT brackets, expressing the same prescription values.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "The preferred aesthetic option for adult patients and self-conscious adolescents. The Premium grade is recommended for cases requiring longer treatment duration or more demanding mechanics where bracket durability is important.",
    tags: [
      "022",
      "mbt",
      "ceramic",
      "kit",
      "economy",
      "brackets"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737997833655IMG_4096.jpeg"
  },
  {
    id: 42,
    name: "Round Bondable Tubes (L / R)",
    slug: "round-bondable-tubes-l-r",
    category: "bands-tubes",
    price: "₹1,800/-",
    sku: "ROUND-BONDABLE-TUBES",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Bondable (adhesive-applied) round molar tubes sold as left and right pairs for upper or lower first molars.",
    clinicalNotes: "A round tube accepts a round archwire, typically in early treatment phases. Bondable tubes are bonded directly to the molar tooth surface, eliminating the need for a cemented molar band.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used when banding is not preferred or when the clinical crown does not accommodate a band. Increasingly common in modern orthodontics.",
    tags: [
      "round",
      "bondable",
      "tubes",
      "bands",
      "and"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-indigo-50 to-indigo-100",
    iconColor: "text-indigo-600",
    image: "1737997904916IMG_4112.jpeg"
  },
  {
    id: 43,
    name: "Crimpable Hooks (Large)",
    slug: "crimpable-hooks-large",
    category: "miscellaneous",
    price: "₹300/-",
    sku: "CRIMPABLE-HOOKS-LARGE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Metal hooks that can be placed and secured at any point along an archwire by crimping (compressing) them in place with a crimpable hooks plier.",
    clinicalNotes: "The hook is threaded onto the archwire, positioned at the ideal location for elastic attachment, and crimped to lock it in place permanently.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Adds elastic attachment points where no bracket hook exists. Particularly useful in non-extraction cases (where fewer hooks are present) or when the ideal elastic vector requires a hook between two brackets. Available in three sizes to accommodate different wire gauges and force requirements.",
    tags: [
      "crimpable",
      "hooks",
      "large",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998072249WhatsApp Image 2025-01-21 at 8.35.04 PM.jpeg"
  },
  {
    id: 44,
    name: "Crimpable Hooks (Medium)",
    slug: "crimpable-hooks-medium",
    category: "miscellaneous",
    price: "₹300/-",
    sku: "CRIMPABLE-HOOKS-MEDIUM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Metal hooks that can be placed and secured at any point along an archwire by crimping (compressing) them in place with a crimpable hooks plier.",
    clinicalNotes: "The hook is threaded onto the archwire, positioned at the ideal location for elastic attachment, and crimped to lock it in place permanently.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Adds elastic attachment points where no bracket hook exists. Particularly useful in non-extraction cases (where fewer hooks are present) or when the ideal elastic vector requires a hook between two brackets. Available in three sizes to accommodate different wire gauges and force requirements.",
    tags: [
      "crimpable",
      "hooks",
      "medium",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998126868WhatsApp Image 2025-01-21 at 8.28.43 PM.jpeg"
  },
  {
    id: 45,
    name: "Crimpable Hooks (Small)",
    slug: "crimpable-hooks-small",
    category: "miscellaneous",
    price: "₹300/-",
    sku: "CRIMPABLE-HOOKS-SMALL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Metal hooks that can be placed and secured at any point along an archwire by crimping (compressing) them in place with a crimpable hooks plier.",
    clinicalNotes: "The hook is threaded onto the archwire, positioned at the ideal location for elastic attachment, and crimped to lock it in place permanently.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Adds elastic attachment points where no bracket hook exists. Particularly useful in non-extraction cases (where fewer hooks are present) or when the ideal elastic vector requires a hook between two brackets. Available in three sizes to accommodate different wire gauges and force requirements.",
    tags: [
      "crimpable",
      "hooks",
      "small",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998171871WhatsApp Image 2025-01-21 at 8.33.44 PM.jpeg"
  },
  {
    id: 46,
    name: "Power Arm (Right)",
    slug: "power-arm-right",
    category: "miscellaneous",
    price: "₹450/-",
    sku: "POWER-ARM-RIGHT",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Small stainless steel auxiliary devices that attach to a bracket slot and extend apically, moving the point of elastic force application toward the center of tooth resistance.",
    clinicalNotes: "Conventional hooks on brackets apply elastics at the bracket level, which can cause unwanted tipping. Power arms extend the attachment point apically, converting the elastic force into a more bodily or root-parallel movement, particularly for en-masse retraction.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used in extraction cases requiring maximum anchorage and bodily retraction of anterior teeth. Left and right versions ensure correct orientation on each side of the arch.",
    tags: [
      "power",
      "arm",
      "right",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998254421WhatsApp Image 2025-01-21 at 8.32.48 PM.jpeg"
  },
  {
    id: 47,
    name: "Power Arm (Left)",
    slug: "power-arm-left",
    category: "miscellaneous",
    price: "₹450/-",
    sku: "POWER-ARM-LEFT",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
     description: "Small stainless steel auxiliary devices that attach to a bracket slot and extend apically, moving the point of elastic force application toward the center of tooth resistance.",
    clinicalNotes: "Conventional hooks on brackets apply elastics at the bracket level, which can cause unwanted tipping. Power arms extend the attachment point apically, converting the elastic force into a more bodily or root-parallel movement, particularly for en-masse retraction.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used in extraction cases requiring maximum anchorage and bodily retraction of anterior teeth. Left and right versions ensure correct orientation on each side of the arch.",
    tags: [
      "power",
      "arm",
      "left",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998310694WhatsApp Image 2025-01-21 at 8.30.42 PM.jpeg"
  },
  {
    id: 48,
    name: "Cheek Retractor",
    slug: "cheek-retractor",
    category: "miscellaneous",
    price: "₹250/-",
    sku: "CHEEK-RETRACTOR",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A flexible plastic retractor that pulls the cheeks and lips away from the teeth to provide unobstructed access and visibility.",
    clinicalNotes: "Inserted into the corners of the mouth and held in place by the patient or assistant, providing a clear field of view for bonding, photography, or intraoral procedures.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Routinely used at bonding appointments for good moisture control and visibility. Also essential for intraoral photography to capture accurate clinical records.",
    tags: [
      "cheek",
      "retractor",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998943208IMG_4135.jpeg"
  },
  {
    id: 49,
    name: "Proximal Strips Double Sided",
    slug: "proximal-strips-double-sided",
    category: "wires-springs",
    price: "₹1,100/-",
    sku: "PROXIMAL-STRIPS-DOUBLE-SIDED",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Proximal Strips Thin, flexible metal strips with abrasive surfaces used for interproximal enamel reduction (IPR). Abrasive on both sides, allowing reduction from both directions but requiring care to protect adjacent teeth.",
    clinicalNotes: "Used to create small amounts of space between teeth without extraction, particularly during alignment of mildly crowded arches. IPR is a controlled and reversible procedure when performed correctly.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "",
    tags: [
      "proximal",
      "strips",
      "double",
      "sided",
      "wires",
      "and"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1737999039146IMG_4149.jpeg"
  },
  {
    id: 50,
    name: "Proximal Strips Safe Sided",
    slug: "proximal-strips-safe-sided",
    category: "wires-springs",
    price: "₹900/-",
    sku: "PROXIMAL-STRIPS-SAFE-SIDED",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Thin, flexible metal strips with abrasive surfaces used for interproximal enamel reduction (IPR). Abrasive on one side only, with a smooth non-cutting side to protect the adjacent tooth surface.",
    clinicalNotes: "Used to create small amounts of space between teeth without extraction, particularly during alignment of mildly crowded arches. IPR is a controlled and reversible procedure when performed correctly.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "",
    tags: [
      "proximal",
      "strips",
      "safe",
      "sided",
      "wires",
      "and"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1737999060410IMG_4152.jpeg"
  },
  {
    id: 51,
    name: "NiTi Close Coil Spring (6mm)",
    slug: "niti-close-coil-spring-6mm",
    category: "wires-springs",
    price: "₹700/-",
    sku: "MITI-CLOSE-COIL-SPRING-6MM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Preformed NiTi closed coil springs available in 6mm and 9mm activated lengths, used for tooth retraction or space closure.",
    clinicalNotes: "The spring is compressed between two attachment points (hooks or brackets). NiTi's superelastic properties ensure the spring delivers a constant, light force over the entire range of deactivation — moving teeth gently and continuously.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used primarily for canine or incisor retraction in extraction cases, or for closing residual spaces after space closure mechanics. NiTi coil springs are preferred over stainless steel because they maintain constant force and do not need reactivation.",
    tags: [
      "niti",
      "close",
      "coil",
      "spring",
      "6mm",
      "wires"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1738514383080IMG_4264.jpeg"
  },
  {
    id: 52,
    name: "Niti Open Coil Spring Spool",
    slug: "niti-open-coil-spring-spool",
    category: "wires-springs",
    price: "₹600/-",
    sku: "NITI-OPEN-COIL-SPRING-SPOOL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A spool of NiTi open coil spring material that can be cut to any desired length chairside.",
    clinicalNotes: "Placed in compression between two teeth or brackets, the spring pushes them apart. The NiTi construction ensures a constant, predictable opening force over the full range of activation.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used to create or regain space — for example, uprighting a tipped molar, reopening a closed extraction site for implant placement, or creating space for a blocked-out canine.",
    tags: [
      "niti",
      "open",
      "coil",
      "spring",
      "spool",
      "wires"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1738514406443IMG_4262.jpeg"
  },
  {
    id: 53,
    name: "Ligature Wire Spool",
    slug: "ligature-wire-spool",
    category: "wires-springs",
    price: "₹300/-",
    sku: "LIGATURE-WIRE-SPOOL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A spool of thin stainless steel wire used to tie archwires into bracket slots.",
    clinicalNotes: "Short lengths are cut from the spool, looped around the bracket wings, and twisted tight with a Mathieu plier or ligature director to hold the archwire securely in the slot.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "The standard ligation method with conventional (non-self-ligating) brackets. Wire ligatures provide more consistent force transmission compared to elastomeric modules and are the ligation of choice in demanding mechanics.",
    tags: [
      "ligature",
      "wire",
      "spool",
      "wires",
      "and",
      "springs"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1738514426175IMG_4261.jpeg"
  },
  {
    id: 54,
    name: "NiTi Close Coil Spring 9mm",
    slug: "niti-close-coil-spring-9mm",
    category: "wires-springs",
    price: "₹700/-",
    sku: "NITI-CLOSE-COIL-SPRING-9MM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Preformed NiTi closed coil springs available in 6mm and 9mm activated lengths, used for tooth retraction or space closure.",
    clinicalNotes: "The spring is compressed between two attachment points (hooks or brackets). NiTi's superelastic properties ensure the spring delivers a constant, light force over the entire range of deactivation — moving teeth gently and continuously.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used primarily for canine or incisor retraction in extraction cases, or for closing residual spaces after space closure mechanics. NiTi coil springs are preferred over stainless steel because they maintain constant force and do not need reactivation.",
    tags: [
      "niti",
      "close",
      "coil",
      "spring",
      "9mm",
      "wires"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1738514445595IMG_4265.jpeg"
  },
  {
    id: 55,
    name: "Coaxial Wire Spool",
    slug: "coaxial-wire-spool",
    category: "wires-springs",
    price: "₹1,200/-",
    sku: "COAIAL-WIRE-SPOOL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A spool of coaxial archwire — a multi-strand wire where several fine wires are twisted or braided around a central core. Properties: Coaxial construction gives the wire high flexibility combined with greater stiffness than a single-strand wire of the same outer diameter. The twisted surface also creates friction that helps engage and move teeth.",
    clinicalNotes: "Used in alignment and leveling phases, particularly in cases where moderate flexibility is desired with slightly more body than a single-strand NiTi wire.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "",
    tags: [
      "coaxial",
      "wire",
      "spool",
      "wires",
      "and",
      "springs"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1738514529696IMG_4133.jpeg"
  },
  {
    id: 56,
    name: "Elastics (1/4 Blue)",
    slug: "elastics-1-4-blue",
    category: "elastics",
    price: "₹400/-",
    sku: "ELASTICS-BLUE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Intraoral orthodontic elastics used by patients to apply inter-arch force.",
    clinicalNotes: "The patient hooks the elastic between upper and lower teeth at specific attachment points (hooks on brackets or buccal tubes). The elastic generates a continuous pulling force that corrects the bite relationship between arches.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used for Class II correction (overbite/overjet), Class III correction, midline discrepancies, and vertical bite problems. Different sizes refer to the inner diameter of the elastic — smaller diameter delivers higher force. Color coding helps patients identify which elastic to use when different forces are prescribed at different stages of treatment.",
    tags: [
      "elastics",
      "1/4",
      "blue",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514565823IMG_4230.jpeg"
  },
  {
    id: 57,
    name: "Yellow Elastics (5/16)",
    slug: "yellow-elastics-5-16",
    category: "elastics",
    price: "₹400/-",
    sku: "YELLOW-ELASTICS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Intraoral orthodontic elastics used by patients to apply inter-arch force.",
    clinicalNotes: "The patient hooks the elastic between upper and lower teeth at specific attachment points (hooks on brackets or buccal tubes). The elastic generates a continuous pulling force that corrects the bite relationship between arches.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used for Class II correction (overbite/overjet), Class III correction, midline discrepancies, and vertical bite problems. Different sizes refer to the inner diameter of the elastic — smaller diameter delivers higher force. Color coding helps patients identify which elastic to use when different forces are prescribed at different stages of treatment.",
    tags: [
      "yellow",
      "elastics",
      "5/16",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514602187IMG_4227.jpeg"
  },
  {
    id: 58,
    name: "Green Elastics (5/16)",
    slug: "green-elastics-5-16",
    category: "elastics",
    price: "₹400/-",
    sku: "GREEN-ELASTICS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Intraoral orthodontic elastics used by patients to apply inter-arch force.",
    clinicalNotes: "The patient hooks the elastic between upper and lower teeth at specific attachment points (hooks on brackets or buccal tubes). The elastic generates a continuous pulling force that corrects the bite relationship between arches.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used for Class II correction (overbite/overjet), Class III correction, midline discrepancies, and vertical bite problems. Different sizes refer to the inner diameter of the elastic — smaller diameter delivers higher force. Color coding helps patients identify which elastic to use when different forces are prescribed at different stages of treatment.",
    tags: [
      "green",
      "elastics",
      "5/16",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514625201IMG_4225.jpeg"
  },
  {
    id: 59,
    name: "Elastics Tooth Color (1/4)",
    slug: "elastics-tooth-color-1-4",
    category: "elastics",
    price: "₹400/-",
    sku: "ELASTICS-TOOTH-COLOR",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Intraoral orthodontic elastics used by patients to apply inter-arch force.",
    clinicalNotes: "The patient hooks the elastic between upper and lower teeth at specific attachment points (hooks on brackets or buccal tubes). The elastic generates a continuous pulling force that corrects the bite relationship between arches.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used for Class II correction (overbite/overjet), Class III correction, midline discrepancies, and vertical bite problems. Different sizes refer to the inner diameter of the elastic — smaller diameter delivers higher force. Color coding helps patients identify which elastic to use when different forces are prescribed at different stages of treatment.",
    tags: [
      "elastics",
      "tooth",
      "color",
      "1/4",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514646225IMG_4226.jpeg"
  },
  {
    id: 60,
    name: "Red Elastics (3/16)",
    slug: "red-elastics-3-16",
    category: "elastics",
    price: "₹400/-",
    sku: "RED-ELASTICS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Intraoral orthodontic elastics used by patients to apply inter-arch force.",
    clinicalNotes: "The patient hooks the elastic between upper and lower teeth at specific attachment points (hooks on brackets or buccal tubes). The elastic generates a continuous pulling force that corrects the bite relationship between arches.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used for Class II correction (overbite/overjet), Class III correction, midline discrepancies, and vertical bite problems. Different sizes refer to the inner diameter of the elastic — smaller diameter delivers higher force. Color coding helps patients identify which elastic to use when different forces are prescribed at different stages of treatment.",
    tags: [
      "red",
      "elastics",
      "3/16",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514675253IMG_4229.jpeg"
  },
  {
    id: 61,
    name: "Tissue Guard",
    slug: "tissue-guard",
    category: "elastics",
    price: "₹800/-",
    sku: "TISSUE-GUARD",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Tissue Guard An elastic accessory placed on the archwire or hook to prevent the wire or hook end from irritating the adjacent soft tissue (cheeks, lips, gingiva).",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used when a hook, wire end, or coil spring is in a position that risks mucosal trauma. The guard acts as a soft buffer between the metal component and the oral mucosa, improving patient comfort between appointments.",
    tags: [
      "tissue",
      "guard",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514698136IMG_4237.jpeg"
  },
  {
    id: 62,
    name: "Modules Grey",
    slug: "modules-grey",
    category: "elastics",
    price: "₹350/-",
    sku: "MODULES-GREY",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Small elastomeric O-rings (ligature modules) used to tie archwires into bracket slots. A neutral color suitable for any patient; less visible than colored modules.",
    clinicalNotes: "Used at every adjustment appointment to re-ligate archwires. Modules are changed at each visit as they degrade and lose elasticity over 4–6 weeks. Clear modules can stain with food and drink; grey maintains its appearance better through the adjustment interval.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "",
    tags: [
      "modules",
      "grey",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738515260829IMG_4142.jpeg"
  },
  {
    id: 63,
    name: "Modules Clear",
    slug: "modules-clear",
    category: "elastics",
    price: "₹350/-",
    sku: "MODULES-CLEAR",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Small elastomeric O-rings (ligature modules) used to tie archwires into bracket slots.Nearly invisible, preferred by patients who want the most discreet appearance possible with metal brackets.",
    clinicalNotes: "Used at every adjustment appointment to re-ligate archwires. Modules are changed at each visit as they degrade and lose elasticity over 4–6 weeks. Clear modules can stain with food and drink; grey maintains its appearance better through the adjustment interval.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "",
    tags: [
      "modules",
      "clear",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738515285082IMG_4140.jpeg"
  },
  {
    id: 68,
    name: "Tear Drop Aligner Plier",
    slug: "tear-drop-aligner-plier",
    category: "pliers",
    price: "₹7,000/-",
    sku: "TEAR-DROP-ALIGNER-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A specialized set of five pliers designed exclusively for use with clear aligner therapy (e.g., Invisalign-style systems). Each plier targets a specific type of fit issue.",
    clinicalNotes: "Creates a teardrop-shaped indent in the aligner to improve attachment seating and tracking.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "These pliers are essential for orthodontists and dentists providing clear aligner treatment. Properly fitting aligners are critical for accurate tooth movement, and these instruments allow chairside adjustment without requiring a new tray from the lab.",
    tags: [
      "tear",
      "drop",
      "aligner",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1738515523893IMG_4235.jpeg"
  },
  {
    id: 69,
    name: "Retention Aligner Plier",
    slug: "retention-aligner-plier",
    category: "pliers",
    price: "₹7,000/-",
    sku: "RETENTION-ALIGNER-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A specialized set of five pliers designed exclusively for use with clear aligner therapy (e.g., Invisalign-style systems). Each plier targets a specific type of fit issue.",
    clinicalNotes: "Improves overall aligner retention and fit around teeth with difficult anatomy.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "These pliers are essential for orthodontists and dentists providing clear aligner treatment. Properly fitting aligners are critical for accurate tooth movement, and these instruments allow chairside adjustment without requiring a new tray from the lab.",
    tags: [
      "retention",
      "aligner",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1738515539077IMG_4231.jpeg"
  },
  {
    id: 70,
    name: "Vertical Aligner Plier",
    slug: "vertical-aligner-plier",
    category: "pliers",
    price: "₹7,000/-",
    sku: "VERTICAL-ALIGNER-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A specialized set of five pliers designed exclusively for use with clear aligner therapy (e.g., Invisalign-style systems). Each plier targets a specific type of fit issue.",
    clinicalNotes: "Adjusts the aligner's vertical fit on the facial surface of teeth.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "These pliers are essential for orthodontists and dentists providing clear aligner treatment. Properly fitting aligners are critical for accurate tooth movement, and these instruments allow chairside adjustment without requiring a new tray from the lab.",
    tags: [
      "vertical",
      "aligner",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1738515553336IMG_4234.jpeg"
  },
  {
    id: 71,
    name: "Horizontal Aligner Plier",
    slug: "horizontal-aligner-plier",
    category: "pliers",
    price: "₹7,000/-",
    sku: "HORIZONTAL-ALIGNER-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A specialized set of five pliers designed exclusively for use with clear aligner therapy (e.g., Invisalign-style systems). Each plier targets a specific type of fit issue.",
    clinicalNotes: "Adjusts the horizontal margins of the aligner, particularly at the gingival edge.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "These pliers are essential for orthodontists and dentists providing clear aligner treatment. Properly fitting aligners are critical for accurate tooth movement, and these instruments allow chairside adjustment without requiring a new tray from the lab.",
    tags: [
      "horizontal",
      "aligner",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1738515591876IMG_4233.jpeg"
  },
  {
    id: 72,
    name: "Hole Punch Aligner Plier",
    slug: "hole-punch-aligner-plier",
    category: "pliers",
    price: "₹7,000/-",
    sku: "HOLE-PUNCH-ALIGNER-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A specialized set of five pliers designed exclusively for use with clear aligner therapy (e.g., Invisalign-style systems). Each plier targets a specific type of fit issue.",
    clinicalNotes: "Creates small ventilation holes in the aligner to allow air circulation or assist with difficult seating.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "These pliers are essential for orthodontists and dentists providing clear aligner treatment. Properly fitting aligners are critical for accurate tooth movement, and these instruments allow chairside adjustment without requiring a new tray from the lab.",
    tags: [
      "hole",
      "punch",
      "aligner",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1738515617754IMG_4236.jpeg"
  },
  {
    id: 73,
    name: "Bondable Molar Brackets (set of 4)",
    slug: "bondable-molar-brackets-set-of-4",
    category: "bands-tubes",
    price: "₹350/-",
    sku: "BONDABLE-MOLAR-BRACKETS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "A set of four bondable brackets designed for molar teeth, providing a bracket slot for archwire engagement on molars where conventional buccal tubes are not used.",
    clinicalNotes: "Used in select cases requiring specific molar tooth movement (e.g., molar rotation, uprighting). Provides more active control over molar position than a simple tube.",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "",
    tags: [
      "bondable",
      "molar",
      "brackets",
      "set",
      "bands",
      "and"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-indigo-50 to-indigo-100",
    iconColor: "text-indigo-600",
    image: "1738515797588IMG_4258.jpeg"
  },
  {
    id: 74,
    name: "MBT 2nd Molar Tubes Single (weldable)",
    slug: "mbt-2nd-molar-tubes-single-weldable",
    category: "bands-tubes",
    price: "₹75/-",
    sku: "MOLAR-TUBES-SINGLE-WELDABLE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Single (non-convertible) buccal tubes designed for welding onto second molar bands. Sold per piece.",
    clinicalNotes: "Welded onto a stainless steel molar band in the lab before cementation, these tubes provide the archwire slot for the second molar. Single tubes have one slot only (no accessory slot for headgear or lip bumper).",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used whenever second molar bands are part of the treatment plan — particularly in cases requiring second molar anchorage or when the second molar must be included in the arch mechanics.",
    tags: [
      "mbt",
      "2nd",
      "molar",
      "tubes",
      "single",
      "weldable"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-indigo-50 to-indigo-100",
    iconColor: "text-indigo-600",
    image: "1738515921181IMG_4251.jpeg"
  },
  {
    id: 75,
    name: "MBT 2nd Molar Tubes Single (weldable)",
    slug: "mbt-2nd-molar-tubes-single-weldable",
    category: "bands-tubes",
    price: "₹75/-",
    sku: "MOLAR-TUBES-SINGLE-WELDABLE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Single (non-convertible) buccal tubes designed for welding onto second molar bands. Sold per piece.",
    clinicalNotes: "Welded onto a stainless steel molar band in the lab before cementation, these tubes provide the archwire slot for the second molar.Single tubes have one slot only (no accessory slot for headgear or lip bumper) ",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    use: "Used whenever second molar bands are part of the treatment plan — particularly in cases requiring second molar anchorage or when the second molar must be included in the arch mechanics.",
    tags: [
      "mbt",
      "2nd",
      "molar",
      "tubes",
      "single",
      "weldable"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-indigo-50 to-indigo-100",
    iconColor: "text-indigo-600",
    image: "1738515936093IMG_4252.jpeg"
  },
];