export const products = [
  {
    id: 1,
    name: "Ligature Director Double Ended plier curved",
    slug: "ligature-director-double-ended-plier-curved",
    category: "pliers",
    price: "₹1,200/-",
    sku: "LIGATURE DIRECTOR DOUBLE ENDED",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "ligature",
      "director",
      "double",
      "ended",
      "plier",
      "curved"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1726158387509WhatsApp Image 2024-09-12 at 7.55.11 PM 1.png"
  },
  {
    id: 2,
    name: "Ligature Director Scaler",
    slug: "ligature-director-scaler",
    category: "pliers",
    price: "₹1,200/-",
    sku: "LIGATURE-DIRECTOR-SCALER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "ligature",
      "director",
      "scaler",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1726158796044WhatsApp Image 2024-09-12 at 7.55.40 PM 1.png"
  },
  {
    id: 3,
    name: "Face Masks",
    slug: "face-masks",
    category: "health-and-hygiene",
    price: "₹10/-",
    sku: "FACE-MASKS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "BREATHABLE :: Soft and comfortable to your face, very effortless breathable to wear.\nPROTECTIVE MASK :: Our Mask keeps you safe from air particles such as smog, dust, smells, vehicle exhaust, pollen, etc.\nADVANTAGE :: Allowing smooth breathing, reducing heat and moisture accumulation.\nWIDE APPLICATION :: This mask is ideal for both women and men, suitable for cycling, camping, running, travel, climbing and daily use.\n",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "face",
      "masks",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1727960502878pink-color-n95-face-mask.jpg"
  },
  {
    id: 4,
    name: "Plier Stand",
    slug: "plier-stand",
    category: "miscellaneous",
    price: "₹800/-",
    sku: "PLIER-STAND",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Designed for maximum comfort and safety.\nThe  quality of steel has a crucial effect on the quality of instruments.\nThe steel is rust proof and provides durability and long lasting performance.\nNew pleasant glassy mat sand finish.\nAll instruments are guaranteed against manufacturing defects.\nProper handling and the correct use of cleaning solutions are the most important thing to consider to ensure a long life time of the instrument.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "plier",
      "stand",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1727960693334image 29.png"
  },
  {
    id: 5,
    name: "Ortho Wax",
    slug: "ortho-wax",
    category: "miscellaneous",
    price: "₹50/-",
    sku: "ORTHO-WAX",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Non-toxic if swallowed.\nThe wax is opaque and unscented/unflavored.\nRemember to remove the wax before you brush your teeth.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "ortho",
      "wax",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1727960950654ortho_wax.jpg"
  },
  {
    id: 6,
    name: "Seprators Blue (pkt of 1000)",
    slug: "seprators-blue-pkt-of-1000",
    category: "elastics",
    price: "₹900/-",
    sku: "SEPRATORS-BLUE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Color: Blue.\nMaterial - elastomers.\nApplication - tying.\nUsage for - around the tooth to make space for bracket.\nPackage contents: 1000pcs.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "seprators",
      "blue",
      "pkt",
      "1000",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1727963927129WhatsApp Image 2024-10-03 at 7.20.47 PM.jpeg"
  },
  {
    id: 7,
    name: "Australian Wire Spool (Special Plus)",
    slug: "australian-wire-spool-special-plus",
    category: "wires-springs",
    price: "₹1,700/-",
    sku: "AUSTRALIAN-WIRE-SPOOL-SPECIAL-PLUS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "AJ Wilcock Special Plus Wire Yellow 25 Ft. Orthodontic Wires are precision-engineered orthodontic wires designed to provide optimal flexibility and resilience for various dental treatments. Crafted by AJ Wilcock, these wires offer orthodontic professionals a reliable solution for achieving controlled tooth movement.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "australian",
      "wire",
      "spool",
      "special",
      "plus",
      "wires"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1727964234449WhatsApp Image 2024-10-03 at 7.15.11 PM.jpeg"
  },
  {
    id: 8,
    name: "NiTi Wire Spool",
    slug: "niti-wire-spool",
    category: "wires-springs",
    price: "₹600/-",
    sku: "NITI-WIRE-SPOOL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "NiTi Straight Wires for professional Orthodontists",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "niti",
      "wire",
      "spool",
      "wires",
      "and",
      "springs"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1727964462392WhatsApp Image 2024-10-03 at 7.19.02 PM.jpeg"
  },
  {
    id: 9,
    name: "TMA Wire Straight",
    slug: "tma-wire-straight",
    category: "wires-springs",
    price: "₹800/-",
    sku: "TMA-WIRE-STRAIGHT",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Length - 7''.\nPacket of 10.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "tma",
      "wire",
      "straight",
      "wires",
      "and",
      "springs"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1727964896028WhatsApp Image 2024-10-03 at 7.22.57 PM.jpeg"
  },
  {
    id: 10,
    name: "Soldering Twizer",
    slug: "soldering-twizer",
    category: "pliers",
    price: "₹800/-",
    sku: "SOLDERING-TWIZER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "soldering",
      "twizer",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994514027IMG_4203.jpeg"
  },
  {
    id: 11,
    name: "Gracy Curette (set of 8)",
    slug: "gracy-curette-set-of-8",
    category: "pliers",
    price: "₹2,000/-",
    sku: "GRACY-CURETTE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Gracy Curette (set of 8)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "gracy",
      "curette",
      "set",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994534626IMG_4200.jpeg"
  },
  {
    id: 12,
    name: "Distal End Bender",
    slug: "distal-end-bender",
    category: "pliers",
    price: "₹1,200/-",
    sku: "DISTAL-END-BENDER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "distal",
      "end",
      "bender",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994557968IMG_4199.jpeg"
  },
  {
    id: 13,
    name: "Ligature Directer(double ended)",
    slug: "ligature-directer-double-ended",
    category: "pliers",
    price: "₹1,200/-",
    sku: "LIGATURE-DIRECTER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Ligature Directer(double ended)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "ligature",
      "directer",
      "double",
      "ended",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994601534IMG_4198.jpeg"
  },
  {
    id: 14,
    name: "Band Seater",
    slug: "band-seater",
    category: "pliers",
    price: "₹400/-",
    sku: "BAND-SEATER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "band",
      "seater",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994666201IMG_4197.jpeg"
  },
  {
    id: 15,
    name: "Distal End Cutter (long handle with safety hold)",
    slug: "distal-end-cutter-long-handle-with-safety-hold",
    category: "pliers",
    price: "₹5,500/-",
    sku: "DISTAL-END-CUTTER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "distal",
      "end",
      "cutter",
      "long",
      "handle",
      "with"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994786742IMG_4195.jpeg"
  },
  {
    id: 16,
    name: "How Plier Straight",
    slug: "how-plier-straight",
    category: "pliers",
    price: "₹1,500/-",
    sku: "HOW-PLIER-STRAIGHT",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "how",
      "plier",
      "straight",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994811265IMG_4194.jpeg"
  },
  {
    id: 17,
    name: "Bracket Placing Twizer",
    slug: "bracket-placing-twizer",
    category: "pliers",
    price: "₹800/-",
    sku: "BRACKET-PLACING-TWIZER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "bracket",
      "placing",
      "twizer",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994832159IMG_4193.jpeg"
  },
  {
    id: 18,
    name: "De-Bonding Plier",
    slug: "de-bonding-plier",
    category: "pliers",
    price: "₹1,500/-",
    sku: "DE-BONDING-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "de-bonding",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994853499IMG_4192.jpeg"
  },
  {
    id: 19,
    name: "MBT Gauge",
    slug: "mbt-gauge",
    category: "pliers",
    price: "₹1,200/-",
    sku: "MBT-GUAGE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "mbt",
      "gauge",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994880415IMG_4191.jpeg"
  },
  {
    id: 20,
    name: "Band Removing Plier",
    slug: "band-removing-plier",
    category: "pliers",
    price: "₹1,500/-",
    sku: "BAND-REMOVING-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "band",
      "removing",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994922953IMG_4188.jpeg"
  },
  {
    id: 21,
    name: "Mathew Plier (with ring)",
    slug: "mathew-plier-with-ring",
    category: "pliers",
    price: "₹1,900/-",
    sku: "MATHEW-PLIER-WITH-RING",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "mathew",
      "plier",
      "with",
      "ring",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737994949454IMG_4187.jpeg"
  },
  {
    id: 22,
    name: "MBT Gauge Aluminium",
    slug: "mbt-gauge-aluminium",
    category: "pliers",
    price: "₹2,400/-",
    sku: "MBT-GAUGE-ALUMINIUM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "mbt",
      "gauge",
      "aluminium",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995003279IMG_4185.jpeg"
  },
  {
    id: 23,
    name: "Band Pusher",
    slug: "band-pusher",
    category: "pliers",
    price: "₹700/-",
    sku: "BAND-PUSHER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "band",
      "pusher",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995031981IMG_4184.jpeg"
  },
  {
    id: 24,
    name: "Band Cutting Scissors",
    slug: "band-cutting-scissors",
    category: "pliers",
    price: "₹800/-",
    sku: "BAND-CUTTING-SCISSORS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "band",
      "cutting",
      "scissors",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995086623IMG_4183.jpeg"
  },
  {
    id: 25,
    name: "Light Wire Plier",
    slug: "light-wire-plier",
    category: "pliers",
    price: "₹1,500/-",
    sku: "LIGHT-WIRE-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "light",
      "wire",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995121028IMG_4182.jpeg"
  },
  {
    id: 26,
    name: "Heavy Wire Cutter",
    slug: "heavy-wire-cutter",
    category: "pliers",
    price: "₹2,000/-",
    sku: "HEAVY-WIRE-CUTTER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "heavy",
      "wire",
      "cutter",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995150116IMG_4181.jpeg"
  },
  {
    id: 27,
    name: "Crimpable Hooks Plier",
    slug: "crimpable-hooks-plier",
    category: "pliers",
    price: "₹2,400/-",
    sku: "CRIMPABLE-HOOKS-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "crimpable",
      "hooks",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995183539IMG_4180.jpeg"
  },
  {
    id: 28,
    name: "Ligature Wire Cutter",
    slug: "ligature-wire-cutter",
    category: "pliers",
    price: "₹5,000/-",
    sku: "LIGATURE-WIRE-CUTTER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "ligature",
      "wire",
      "cutter",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995217108IMG_4179.jpeg"
  },
  {
    id: 29,
    name: "Hard Wire Cutter",
    slug: "hard-wire-cutter",
    category: "pliers",
    price: "₹5,000/-",
    sku: "HARD-WIRE-CUTTER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "hard",
      "wire",
      "cutter",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995251702IMG_4178.jpeg"
  },
  {
    id: 30,
    name: "Wiengart Plier",
    slug: "wiengart-plier",
    category: "pliers",
    price: "₹2,200/-",
    sku: "WIENGART-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "wiengart",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995280032IMG_4177.jpeg"
  },
  {
    id: 31,
    name: "Ligature Forming Plier",
    slug: "ligature-forming-plier",
    category: "pliers",
    price: "₹2,500/-",
    sku: "LIGATURE-FORMING-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "ligature",
      "forming",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995305007IMG_4176.jpeg"
  },
  {
    id: 32,
    name: "Band Crimping Plier",
    slug: "band-crimping-plier",
    category: "pliers",
    price: "₹1,600/-",
    sku: "BAND-CRIMPING-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "band",
      "crimping",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995339272IMG_4175.jpeg"
  },
  {
    id: 33,
    name: "Buccal tube Placing Twizer",
    slug: "buccal-tube-placing-twizer",
    category: "pliers",
    price: "₹900/-",
    sku: "BUCCAL-TUBE-PLACING-TWIZER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "buccal",
      "tube",
      "placing",
      "twizer",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1737995362129IMG_4173.jpeg"
  },
  {
    id: 34,
    name: "Lingual Buttons",
    slug: "lingual-buttons",
    category: "miscellaneous",
    price: "₹1,000/-",
    sku: "LINGUAL-BUTTONS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Lingual Buttons",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "lingual",
      "buttons",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737996377484IMG_4111.jpeg"
  },
  {
    id: 35,
    name: "Lingual Buttons Metal",
    slug: "lingual-buttons-metal",
    category: "miscellaneous",
    price: "₹300/-",
    sku: "LINGUAL-BUTTONS-METAL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Lingual Buttons Metal",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "lingual",
      "buttons",
      "metal",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737996440881IMG_4122.jpeg"
  },
  {
    id: 36,
    name: "022 MBT Kit Galaxy",
    slug: "022-mbt-kit-galaxy",
    category: "brackets",
    price: "₹400/-",
    sku: "GALAXY",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "022 MBT Kit Galaxy",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "022",
      "mbt",
      "kit",
      "galaxy",
      "brackets"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737996898446IMG_4115.jpeg"
  },
  {
    id: 37,
    name: "022 MBT Self Ligating Ceramic Kit Premium",
    slug: "022-mbt-self-ligating-ceramic-kit-premium",
    category: "brackets",
    price: "₹11,000/-",
    sku: "SELF-LIGATING-CERAMIC-PREMIUM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "022 MBT Self Ligating Ceramic Kit Premium",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "022",
      "mbt",
      "self",
      "ligating",
      "ceramic",
      "kit"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737997363627IMG_4113.jpeg"
  },
  {
    id: 38,
    name: "022 MBT Ceramic Kit Premium",
    slug: "022-mbt-ceramic-kit-premium",
    category: "brackets",
    price: "₹2,000/-",
    sku: "CERAMIC-KIT-PREMIUM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "022 MBT Ceramic Kit Premium",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "022",
      "mbt",
      "ceramic",
      "kit",
      "premium",
      "brackets"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737997438140IMG_4098.jpeg"
  },
  {
    id: 39,
    name: "022 MBT Self Ligating Kit",
    slug: "022-mbt-self-ligating-kit",
    category: "brackets",
    price: "₹3,500/-",
    sku: "SELF-LIGATING-KIT",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "022 MBT Self Ligating Kit",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "022",
      "mbt",
      "self",
      "ligating",
      "kit",
      "brackets"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737997535054IMG_4106.jpeg"
  },
  {
    id: 40,
    name: "022 MBT Ceramic Kit Clear",
    slug: "022-mbt-ceramic-kit-clear",
    category: "brackets",
    price: "₹2,600/-",
    sku: "CERAMIC-KIT-CLEAR",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "022 MBT Ceramic Kit Clear",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "022",
      "mbt",
      "ceramic",
      "kit",
      "clear",
      "brackets"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737997604210IMG_4100.jpeg"
  },
  {
    id: 41,
    name: "022 MBT Ceramic Kit Economy",
    slug: "022-mbt-ceramic-kit-economy",
    category: "brackets",
    price: "₹900/-",
    sku: "CERAMIC-KIT-ECONOMY",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "022 MBT Ceramic Kit Economy",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "022",
      "mbt",
      "ceramic",
      "kit",
      "economy",
      "brackets"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-blue-50 to-blue-100",
    iconColor: "text-blue-600",
    image: "1737997833655IMG_4096.jpeg"
  },
  {
    id: 42,
    name: "Round Bondable Tubes (L / R)",
    slug: "round-bondable-tubes-l-r",
    category: "bands-tubes",
    price: "₹1,800/-",
    sku: "ROUND-BONDABLE-TUBES",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Round Bondable Tubes (L / R)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "round",
      "bondable",
      "tubes",
      "bands",
      "and"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-indigo-50 to-indigo-100",
    iconColor: "text-indigo-600",
    image: "1737997904916IMG_4112.jpeg"
  },
  {
    id: 43,
    name: "Crimpable Hooks (Large)",
    slug: "crimpable-hooks-large",
    category: "miscellaneous",
    price: "₹300/-",
    sku: "CRIMPABLE-HOOKS-LARGE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Crimpable Hooks (Large)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "crimpable",
      "hooks",
      "large",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998072249WhatsApp Image 2025-01-21 at 8.35.04 PM.jpeg"
  },
  {
    id: 44,
    name: "Crimpable Hooks (Medium)",
    slug: "crimpable-hooks-medium",
    category: "miscellaneous",
    price: "₹300/-",
    sku: "CRIMPABLE-HOOKS-MEDIUM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Crimpable Hooks (Medium)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "crimpable",
      "hooks",
      "medium",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998126868WhatsApp Image 2025-01-21 at 8.28.43 PM.jpeg"
  },
  {
    id: 45,
    name: "Crimpable Hooks (Small)",
    slug: "crimpable-hooks-small",
    category: "miscellaneous",
    price: "₹300/-",
    sku: "CRIMPABLE-HOOKS-SMALL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Crimpable Hooks (Small)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "crimpable",
      "hooks",
      "small",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998171871WhatsApp Image 2025-01-21 at 8.33.44 PM.jpeg"
  },
  {
    id: 46,
    name: "Power Arm (Right)",
    slug: "power-arm-right",
    category: "miscellaneous",
    price: "₹450/-",
    sku: "POWER-ARM-RIGHT",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Power Arm (Right)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "power",
      "arm",
      "right",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998254421WhatsApp Image 2025-01-21 at 8.32.48 PM.jpeg"
  },
  {
    id: 47,
    name: "Power Arm (Left)",
    slug: "power-arm-left",
    category: "miscellaneous",
    price: "₹450/-",
    sku: "POWER-ARM-LEFT",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Power Arm (Left)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "power",
      "arm",
      "left",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998310694WhatsApp Image 2025-01-21 at 8.30.42 PM.jpeg"
  },
  {
    id: 48,
    name: "Cheek Retractor",
    slug: "cheek-retractor",
    category: "miscellaneous",
    price: "₹250/-",
    sku: "CHEEK-RETRACTOR",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Cheek Retractor for optimal visibility and access during dental procedures.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "cheek",
      "retractor",
      "miscellaneous"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-orange-50 to-orange-100",
    iconColor: "text-orange-600",
    image: "1737998943208IMG_4135.jpeg"
  },
  {
    id: 49,
    name: "Proximal Strips Double Sided",
    slug: "proximal-strips-double-sided",
    category: "wires-springs",
    price: "₹1,100/-",
    sku: "PROXIMAL-STRIPS-DOUBLE-SIDED",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Proximal Strips Double Sided",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "proximal",
      "strips",
      "double",
      "sided",
      "wires",
      "and"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1737999039146IMG_4149.jpeg"
  },
  {
    id: 50,
    name: "Proximal Strips Safe Sided",
    slug: "proximal-strips-safe-sided",
    category: "wires-springs",
    price: "₹900/-",
    sku: "PROXIMAL-STRIPS-SAFE-SIDED",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Proximal Strips Safe Sided",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "proximal",
      "strips",
      "safe",
      "sided",
      "wires",
      "and"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1737999060410IMG_4152.jpeg"
  },
  {
    id: 51,
    name: "NiTi Close Coil Spring (6mm)",
    slug: "niti-close-coil-spring-6mm",
    category: "wires-springs",
    price: "₹700/-",
    sku: "MITI-CLOSE-COIL-SPRING-6MM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "NiTi Close Coil Spring (6mm). Packet of 10",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "niti",
      "close",
      "coil",
      "spring",
      "6mm",
      "wires"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1738514383080IMG_4264.jpeg"
  },
  {
    id: 52,
    name: "Niti Open Coil Spring Spool",
    slug: "niti-open-coil-spring-spool",
    category: "wires-springs",
    price: "₹600/-",
    sku: "NITI-OPEN-COIL-SPRING-SPOOL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Niti Open Coil Spring Spool",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "niti",
      "open",
      "coil",
      "spring",
      "spool",
      "wires"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1738514406443IMG_4262.jpeg"
  },
  {
    id: 53,
    name: "Ligature Wire Spool",
    slug: "ligature-wire-spool",
    category: "wires-springs",
    price: "₹300/-",
    sku: "LIGATURE-WIRE-SPOOL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Ligature Wire Spool",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "ligature",
      "wire",
      "spool",
      "wires",
      "and",
      "springs"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1738514426175IMG_4261.jpeg"
  },
  {
    id: 54,
    name: "NiTi Close Coil Spring 9mm",
    slug: "niti-close-coil-spring-9mm",
    category: "wires-springs",
    price: "₹700/-",
    sku: "NITI-CLOSE-COIL-SPRING-9MM",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Niti Close Coil Spring 9mm. Packet of 10.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "niti",
      "close",
      "coil",
      "spring",
      "9mm",
      "wires"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1738514445595IMG_4265.jpeg"
  },
  {
    id: 55,
    name: "Coaxial Wire Spool",
    slug: "coaxial-wire-spool",
    category: "wires-springs",
    price: "₹1,200/-",
    sku: "COAIAL-WIRE-SPOOL",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Coaxial Wire Spool",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "coaxial",
      "wire",
      "spool",
      "wires",
      "and",
      "springs"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-slate-50 to-slate-100",
    iconColor: "text-slate-600",
    image: "1738514529696IMG_4133.jpeg"
  },
  {
    id: 56,
    name: "Elastics (1/4 Blue)",
    slug: "elastics-1-4-blue",
    category: "elastics",
    price: "₹400/-",
    sku: "ELASTICS-BLUE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Elastics (1/4 Blue)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "elastics",
      "1/4",
      "blue",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514565823IMG_4230.jpeg"
  },
  {
    id: 57,
    name: "Yellow Elastics (5/16)",
    slug: "yellow-elastics-5-16",
    category: "elastics",
    price: "₹400/-",
    sku: "YELLOW-ELASTICS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Yellow Elastics (5/16)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "yellow",
      "elastics",
      "5/16",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514602187IMG_4227.jpeg"
  },
  {
    id: 58,
    name: "Green Elastics (5/16)",
    slug: "green-elastics-5-16",
    category: "elastics",
    price: "₹400/-",
    sku: "GREEN-ELASTICS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Green Elastics (5/16)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "green",
      "elastics",
      "5/16",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514625201IMG_4225.jpeg"
  },
  {
    id: 59,
    name: "Elastics Tooth Color (1/4)",
    slug: "elastics-tooth-color-1-4",
    category: "elastics",
    price: "₹400/-",
    sku: "ELASTICS-TOOTH-COLOR",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Elastics Tooth Color (1/4)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "elastics",
      "tooth",
      "color",
      "1/4",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514646225IMG_4226.jpeg"
  },
  {
    id: 60,
    name: "Red Elastics (3/16)",
    slug: "red-elastics-3-16",
    category: "elastics",
    price: "₹400/-",
    sku: "RED-ELASTICS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Red Elastics (3/16)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "red",
      "elastics",
      "3/16",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514675253IMG_4229.jpeg"
  },
  {
    id: 61,
    name: "Tissue Guard",
    slug: "tissue-guard",
    category: "elastics",
    price: "₹800/-",
    sku: "TISSUE-GUARD",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Tissue Guard",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "tissue",
      "guard",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738514698136IMG_4237.jpeg"
  },
  {
    id: 62,
    name: "Modules Grey",
    slug: "modules-grey",
    category: "elastics",
    price: "₹350/-",
    sku: "MODULES-GREY",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Modules Grey",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "modules",
      "grey",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738515260829IMG_4142.jpeg"
  },
  {
    id: 63,
    name: "Modules Clear",
    slug: "modules-clear",
    category: "elastics",
    price: "₹350/-",
    sku: "MODULES-CLEAR",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Modules Clear",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "modules",
      "clear",
      "elastomerics"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-purple-50 to-purple-100",
    iconColor: "text-purple-600",
    image: "1738515285082IMG_4140.jpeg"
  },
  {
    id: 68,
    name: "Tear Drop Aligner Plier",
    slug: "tear-drop-aligner-plier",
    category: "pliers",
    price: "₹7,000/-",
    sku: "TEAR-DROP-ALIGNER-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "tear",
      "drop",
      "aligner",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1738515523893IMG_4235.jpeg"
  },
  {
    id: 69,
    name: "Retention Aligner Plier",
    slug: "retention-aligner-plier",
    category: "pliers",
    price: "₹7,000/-",
    sku: "RETENTION-ALIGNER-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "retention",
      "aligner",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1738515539077IMG_4231.jpeg"
  },
  {
    id: 70,
    name: "Vertical Aligner Plier",
    slug: "vertical-aligner-plier",
    category: "pliers",
    price: "₹7,000/-",
    sku: "VERTICAL-ALIGNER-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "vertical",
      "aligner",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1738515553336IMG_4234.jpeg"
  },
  {
    id: 71,
    name: "Horizontal Aligner Plier",
    slug: "horizontal-aligner-plier",
    category: "pliers",
    price: "₹7,000/-",
    sku: "HORIZONTAL-ALIGNER-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "horizontal",
      "aligner",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1738515591876IMG_4233.jpeg"
  },
  {
    id: 72,
    name: "Hole Punch Aligner Plier",
    slug: "hole-punch-aligner-plier",
    category: "pliers",
    price: "₹7,000/-",
    sku: "HOLE-PUNCH-ALIGNER-PLIER",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "High Quality Surgical Grade Japanese Steel. Designed for maximum comfort and safety. The quality of steel has a crucial effect on the quality of instruments. Japanese Steel is rust proof and provides durability and long lasting performance. New Pleasant glassy mat sand finish. All instruments are guaranteed against manufacturing defects. Proper handling and the correct use of cleaning solutions are the most important things to consider to ensure a long life of the instruments.",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "hole",
      "punch",
      "aligner",
      "plier",
      "orthodontic",
      "pliers"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-zinc-50 to-zinc-100",
    iconColor: "text-zinc-600",
    image: "1738515617754IMG_4236.jpeg"
  },
  {
    id: 73,
    name: "Bondable Molar Brackets (set of 4)",
    slug: "bondable-molar-brackets-set-of-4",
    category: "bands-tubes",
    price: "₹350/-",
    sku: "BONDABLE-MOLAR-BRACKETS",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "Bondable Molar Brackets (set of 4)",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "bondable",
      "molar",
      "brackets",
      "set",
      "bands",
      "and"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-indigo-50 to-indigo-100",
    iconColor: "text-indigo-600",
    image: "1738515797588IMG_4258.jpeg"
  },
  {
    id: 74,
    name: "MBT 2nd Molar Tubes Single (weldable)",
    slug: "mbt-2nd-molar-tubes-single-weldable",
    category: "bands-tubes",
    price: "₹75/-",
    sku: "MOLAR-TUBES-SINGLE-WELDABLE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "MBT 2nd Molar Tubes Single (weldable) Rs.75 per piece",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "mbt",
      "2nd",
      "molar",
      "tubes",
      "single",
      "weldable"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-indigo-50 to-indigo-100",
    iconColor: "text-indigo-600",
    image: "1738515921181IMG_4251.jpeg"
  },
  {
    id: 75,
    name: "MBT 2nd Molar Tubes Single (weldable)",
    slug: "mbt-2nd-molar-tubes-single-weldable",
    category: "bands-tubes",
    price: "₹75/-",
    sku: "MOLAR-TUBES-SINGLE-WELDABLE",
    stockStatus: "in-stock",
    specs: {},
    shortSpecs: "",
    description: "MBT 2nd Molar Tubes Single (weldable) Rs.75 per piece",
    clinicalNotes: "",
    packaging: "",
    shippingInfo: "Ships in 1-2 business days.",
    compatibility: "",
    tags: [
      "mbt",
      "2nd",
      "molar",
      "tubes",
      "single",
      "weldable"
    ],
    featured: false,
    trending: false,
    newArrival: false,
    bestSeller: false,
    gradient: "from-indigo-50 to-indigo-100",
    iconColor: "text-indigo-600",
    image: "1738515936093IMG_4252.jpeg"
  },
];